begin;
set local search_path=extensions,public,pg_catalog;
select plan(30);
select has_table('public','setc_insurance_adapter_systems','adapter systems table exists');
select has_table('public','setc_insurance_adapter_bindings','adapter bindings table exists');
select has_table('public','setc_insurance_adapter_events','adapter events table exists');
select has_table('public','setc_insurance_adapter_checkpoints','adapter checkpoints table exists');
select has_table('public','setc_insurance_adapter_errors','adapter errors table exists');
select has_table('public','setc_insurance_adapter_settlement_references','adapter settlement references table exists');
select has_table('public','setc_insurance_adapter_asset_references','adapter asset references table exists');
select has_table('public','setc_insurance_adapter_intelligence_references','adapter intelligence references table exists');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_adapter_systems'::regclass),'systems RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_adapter_bindings'::regclass),'bindings RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_adapter_events'::regclass),'events RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_adapter_checkpoints'::regclass),'checkpoints RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_adapter_errors'::regclass),'errors RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_adapter_settlement_references'::regclass),'settlement RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_adapter_asset_references'::regclass),'asset RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_adapter_intelligence_references'::regclass),'intelligence RLS enabled');
select ok(not has_table_privilege('anon','public.setc_insurance_adapter_systems','SELECT'),'anon cannot select systems');
select ok(not has_table_privilege('authenticated','public.setc_insurance_adapter_systems','SELECT'),'authenticated cannot select systems');
select ok(has_table_privilege('service_role','public.setc_insurance_adapter_systems','SELECT'),'service role can select systems');
select ok((select count(*)=0 from pg_policies where schemaname='public' and tablename='setc_insurance_adapter_systems'),'systems has no client RLS policy');
select throws_ok($$insert into public.setc_insurance_adapter_systems(system_code,system_name,domain_type,authority_class) values ('T-AUTH','Test','external','authoritative_external')$$,'23514',null,'authoritative external system requires evidence');
select throws_ok($$insert into public.setc_insurance_adapter_systems(system_code,system_name,domain_type,system_status) values ('T-DOM','Test','bad_domain','draft')$$,'23514',null,'invalid domain rejected');
select throws_ok($$insert into public.setc_insurance_adapter_systems(system_code,system_name,domain_type,system_status) values ('T-STAT','Test','external','bad_status')$$,'23514',null,'invalid system status rejected');
select col_type_is('public','setc_insurance_adapter_settlement_references','amount','numeric(24,6)','settlement amount precision exact');
select col_type_is('public','setc_insurance_adapter_events','payload_hash','text','payload hash is text');
select ok((select count(*)=0 from pg_policies where schemaname='public' and tablename='setc_insurance_adapter_bindings'),'bindings has no client RLS policy');
select ok((select count(*)=0 from pg_policies where schemaname='public' and tablename='setc_insurance_adapter_events'),'events has no client RLS policy');
select ok((select count(*)=0 from pg_policies where schemaname='public' and tablename='setc_insurance_adapter_settlement_references'),'settlement has no client RLS policy');
select ok((select count(*)=0 from pg_policies where schemaname='public' and tablename='setc_insurance_adapter_asset_references'),'asset has no client RLS policy');
select ok((select count(*)=0 from pg_policies where schemaname='public' and tablename='setc_insurance_adapter_intelligence_references'),'intelligence has no client RLS policy');
select * from finish();
rollback;
