begin;
set local search_path=extensions,public,pg_catalog;
select plan(24);
select has_table('public','setc_insurance_readiness_assessments','readiness assessments table exists');
select has_table('public','setc_insurance_readiness_controls','readiness controls table exists');
select has_table('public','setc_insurance_readiness_results','readiness results table exists');
select has_table('public','setc_insurance_recovery_readiness','recovery readiness table exists');
select has_table('public','setc_insurance_operational_readiness','operational readiness table exists');
select has_table('public','setc_insurance_go_live_decisions','go live decisions table exists');
select has_table('public','setc_insurance_post_deployment_verifications','post deployment verification table exists');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_readiness_assessments'::regclass),'readiness assessments RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_readiness_controls'::regclass),'readiness controls RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_readiness_results'::regclass),'readiness results RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_recovery_readiness'::regclass),'recovery readiness RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_operational_readiness'::regclass),'operational readiness RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_go_live_decisions'::regclass),'go live RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_post_deployment_verifications'::regclass),'post deployment RLS enabled');
select ok(not has_table_privilege('anon','public.setc_insurance_readiness_assessments','SELECT'),'anon cannot select readiness assessments');
select ok(not has_table_privilege('authenticated','public.setc_insurance_readiness_assessments','SELECT'),'authenticated cannot select readiness assessments');
select ok(has_table_privilege('service_role','public.setc_insurance_readiness_assessments','SELECT'),'service role can select readiness assessments');
select ok((select count(*)=0 from pg_policies where schemaname='public' and tablename='setc_insurance_readiness_assessments'),'readiness assessments has no client policy');
select throws_ok($$insert into public.setc_insurance_readiness_assessments(organization_oid,release_reference,environment_code,assessment_status) values ('TEST','REL','prod','ready_reference')$$,'23514',null,'ready assessment requires evidence');
select throws_ok($$insert into public.setc_insurance_go_live_decisions(readiness_assessment_id,decision) values ('00000000-0000-0000-0000-000000000001','go_reference')$$,'23514',null,'go decision requires authority and evidence');
select throws_ok($$insert into public.setc_insurance_readiness_controls(control_code,control_name,control_class) values ('BAD','Bad','invalid')$$,'23514',null,'invalid control class rejected');
select throws_ok($$insert into public.setc_insurance_recovery_readiness(readiness_assessment_id,recovery_type,procedure_reference,test_status) values ('00000000-0000-0000-0000-000000000001','rollback','runbook','tested_reference')$$,'23514',null,'tested recovery requires evidence');
select throws_ok($$insert into public.setc_insurance_operational_readiness(readiness_assessment_id,readiness_type,reference_value,status) values ('00000000-0000-0000-0000-000000000001','runbook','RB-1','verified_reference')$$,'23514',null,'verified operational readiness requires evidence');
select throws_ok($$insert into public.setc_insurance_post_deployment_verifications(readiness_assessment_id,verification_type,verification_status) values ('00000000-0000-0000-0000-000000000001','schema','passed_reference')$$,'23514',null,'passed post deployment verification requires evidence');
select * from finish();
rollback;
