begin;
set local search_path = extensions, public, pg_catalog;
select plan(31);
select has_table('public','setc_insurance_analytics_models','analytics models table exists');
select has_table('public','setc_insurance_portfolio_snapshots','portfolio snapshots table exists');
select has_table('public','setc_insurance_concentration_metrics','concentration metrics table exists');
select has_table('public','setc_insurance_performance_metrics','performance metrics table exists');
select has_table('public','setc_insurance_risk_aggregations','risk aggregations table exists');
select has_table('public','setc_insurance_scenarios','scenarios table exists');
select has_table('public','setc_insurance_scenario_results','scenario results table exists');
select has_table('public','setc_insurance_intelligence_lineage','intelligence lineage table exists');
select has_table('public','setc_insurance_intelligence_explanations','intelligence explanations table exists');
select col_type_is('public','setc_insurance_portfolio_snapshots','exposure_amount','numeric(24,6)','portfolio exposure precision is exact');
select col_type_is('public','setc_insurance_concentration_metrics','exposure_pct','numeric(12,8)','concentration percentage precision is exact');
select col_type_is('public','setc_insurance_performance_metrics','metric_value','numeric(30,10)','performance metric precision is exact');
select col_type_is('public','setc_insurance_scenario_results','confidence_score','numeric(9,8)','scenario confidence precision is exact');
select col_type_is('public','setc_insurance_intelligence_explanations','confidence_score','numeric(9,8)','explanation confidence precision is exact');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_analytics_models'::regclass),'analytics models RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_portfolio_snapshots'::regclass),'portfolio snapshots RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_concentration_metrics'::regclass),'concentration metrics RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_performance_metrics'::regclass),'performance metrics RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_risk_aggregations'::regclass),'risk aggregations RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_scenarios'::regclass),'scenarios RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_scenario_results'::regclass),'scenario results RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_intelligence_lineage'::regclass),'lineage RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.setc_insurance_intelligence_explanations'::regclass),'explanations RLS enabled');
select ok(not has_table_privilege('anon','public.setc_insurance_analytics_models','SELECT'),'anon cannot select analytics models');
select ok(not has_table_privilege('authenticated','public.setc_insurance_analytics_models','SELECT'),'authenticated cannot select analytics models');
select ok(has_table_privilege('service_role','public.setc_insurance_analytics_models','SELECT'),'service role can select analytics models');
select throws_ok($$insert into public.setc_insurance_analytics_models(model_code,model_name,model_type,model_version,model_status) values ('TEST-MODEL','Test','stress','1.0','evidence_supported')$$,'23514',null,'evidence-supported model requires validation evidence');
select throws_ok($$insert into public.setc_insurance_intelligence_lineage(artifact_type,artifact_reference,lineage_status) values ('report','TEST','verified_reference')$$,'23514',null,'verified lineage requires evidence');
select ok((select count(*)=0 from pg_policies where schemaname='public' and tablename='setc_insurance_analytics_models'),'analytics model has no client RLS policy');
select ok((select count(*)=0 from pg_policies where schemaname='public' and tablename='setc_insurance_portfolio_snapshots'),'portfolio snapshot has no client RLS policy');
select ok((select count(*)=0 from pg_policies where schemaname='public' and tablename='setc_insurance_scenarios'),'scenario table has no client RLS policy');
select * from finish();
rollback;
