import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./styles.css';
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const money=(n:any,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number(n||0));
function Metric({label,value,sub}:{label:string,value:any,sub?:string}){return <div className="metric"><span>{label}</span><strong>{value??'—'}</strong>{sub&&<small>{sub}</small>}</div>}
function App(){const[session,setSession]=useState<any>(null),[email,setEmail]=useState(''),[tab,setTab]=useState('Command'),[data,setData]=useState<any>({summary:null,clients:[],pipeline:[],crm:[]}),[error,setError]=useState(''),[notice,setNotice]=useState('');
useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:s}=supabase.auth.onAuthStateChange((_e,x)=>setSession(x));return()=>s.subscription.unsubscribe()},[]);
useEffect(()=>{if(!session)return;(async()=>{setError('');const[s,c,p,r]=await Promise.all([supabase.from('wa_executive_command_summary').select('*').maybeSingle(),supabase.from('wa_client_portal_overview').select('*').order('client_updated_at',{ascending:false}).limit(50),supabase.from('wa_capital_pipeline').select('*').order('updated_at',{ascending:false}).limit(100),supabase.from('wa_advisor_crm_queue').select('*').order('last_activity_at',{ascending:false}).limit(100)]);const first=[s,c,p,r].find(x=>x.error);if(first?.error)setError(first.error.message);setData({summary:s.data,clients:c.data||[],pipeline:p.data||[],crm:r.data||[]})})()},[session]);
if(!session)return <main className="login"><section><div className="brand">SOURCEENERGY <b>WEALTH ADVISORS</b></div><h1>Governed wealth infrastructure for people, enterprises and communities.</h1><p>Access is invitation-only. Enter the email address already provisioned by SourceEnergy Wealth Advisors.</p><form onSubmit={async e=>{e.preventDefault();setError('');setNotice('');const{error}=await supabase.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:window.location.origin}});if(error)setError(error.message);else setNotice('Secure sign-in link sent. Check your email.')}}><input type="email" placeholder="Approved email" value={email} onChange={e=>setEmail(e.target.value)} required/><button>Send secure sign-in link</button>{notice&&<p>{notice}</p>}{error&&<em>{error}</em>}</form></section></main>;
const s=data.summary||{};return <div className="app"><aside><div className="brand">SOURCEENERGY <b>WEALTH ADVISORS</b></div><nav>{['Command','Clients','Advisor CRM','Capital'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><div className="user">Authenticated<br/><b>{session.user.email}</b><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div></aside><main><header><div><small>WEALTH ECOLOGY / GOVERNED OPERATIONS</small><h1>{tab}</h1></div><span className="live">● LIVE DATA PLANE</span></header>{error&&<div className="alert">Access/data notice: {error}</div>}
{tab==='Command'&&<><div className="grid"><Metric label="Active clients" value={s.active_clients}/><Metric label="Average FRI" value={s.average_fri_score}/><Metric label="Capital requested" value={money(s.capital_requested)}/><Metric label="Capital funded" value={money(s.capital_funded)}/><Metric label="Verified outcomes" value={s.verified_outcomes}/><Metric label="Open compliance" value={s.open_compliance_events}/></div><section className="panel"><h2>Capital conversion</h2><div className="stages">{[['Requested',s.capital_requested],['Referred',s.capital_referred],['Approved',s.capital_approved],['Closed',s.capital_closed],['Funded',s.capital_funded]].map(([a,b])=><div key={String(a)}><span>{a}</span><b>{money(b)}</b></div>)}</div></section></>}
{tab==='Clients'&&<section className="panel"><h2>Client portfolio</h2><div className="cards">{data.clients.map((c:any)=><article key={c.client_id}><small>{c.client_type} · {c.geographic_market||'Market pending'}</small><h3>{c.preferred_name||'Client'}</h3><p>FRI <b>{c.latest_fri_score??'—'}</b> · {c.latest_fri_classification||'Not assessed'}</p><p>{c.primary_pathway||'Pathway pending'}</p><footer>{c.open_actions} actions · {c.verified_documents}/{c.total_documents} verified</footer></article>)}</div></section>}
{tab==='Advisor CRM'&&<section className="panel"><h2>Advisor work queue</h2><Table rows={data.crm} cols={['preferred_name','latest_fri_score','primary_pathway','open_actions','next_action_due_date','open_referrals','open_compliance_events']}/></section>}
{tab==='Capital'&&<section className="panel"><h2>Capital pipeline</h2><Table rows={data.pipeline} cols={['client_name','enterprise_name','amount_requested','currency','requested_structure','readiness_status','funded_amount']}/></section>}</main></div>}
function Table({rows,cols}:{rows:any[],cols:string[]}){return <div className="tablewrap"><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||r.client_id||i}>{cols.map(c=><td key={c}>{r[c]??'—'}</td>)}</tr>)}</tbody></table></div>}
createRoot(document.getElementById('root')!).render(<App/>);
