-- Public-safe Capitalization Block API projection and security boundary.
-- Only registry metadata and non-financial system metrics are published.
-- No balances, commitments, account references, evidence documents, settlement
-- instructions, credentials, or secrets are exposed here.

BEGIN;

REVOKE ALL ON SCHEMA capitalization_api FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA capitalization_api TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA capitalization_api
    REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA capitalization_api
    REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA capitalization_api
    REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, anon, authenticated;

CREATE TABLE IF NOT EXISTS capitalization_api.network_directory (
    directory_entry_id text PRIMARY KEY,
    institution_reference text NOT NULL,
    institution_display_name text NOT NULL,
    institution_type text NOT NULL,
    jurisdiction_code text,
    region_code text,
    sourceenergy_node_id text NOT NULL,
    dominion_cube_id text,
    relay_code text,
    layer_number integer,
    operational_role text,
    relationship_state text NOT NULL,
    connectivity_status text NOT NULL,
    verification_status text NOT NULL,
    public_claim_status text NOT NULL,
    relationship_label text NOT NULL,
    connectivity_label text NOT NULL,
    last_verified_at timestamptz,
    disclosure text NOT NULL,
    is_published boolean NOT NULL DEFAULT true,
    published_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT capitalization_api_network_directory_claim_chk CHECK (
        public_claim_status IN (
            'REGISTRY_TARGET', 'EVIDENCE_BACKED_NON_LIVE', 'VERIFIED_LIVE'
        )
    ),
    CONSTRAINT capitalization_api_network_directory_live_chk CHECK (
        public_claim_status <> 'VERIFIED_LIVE'
        OR (
            relationship_state = 'LIVE'
            AND connectivity_status = 'PRODUCTION'
            AND verification_status = 'VERIFIED'
            AND last_verified_at IS NOT NULL
        )
    )
);

CREATE TABLE IF NOT EXISTS capitalization_api.dashboard_metrics (
    metric_code text PRIMARY KEY,
    metric_name text NOT NULL,
    numeric_value numeric(38, 12),
    text_value text,
    unit text,
    measurement_kind text NOT NULL DEFAULT 'SYSTEM_DERIVED',
    as_of timestamptz NOT NULL,
    disclosure text NOT NULL,
    is_published boolean NOT NULL DEFAULT true,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT capitalization_api_dashboard_metrics_value_chk CHECK (
        numeric_value IS NOT NULL OR text_value IS NOT NULL
    ),
    CONSTRAINT capitalization_api_dashboard_metrics_kind_chk CHECK (
        measurement_kind IN ('SYSTEM_DERIVED', 'OBSERVED', 'VERIFIED')
    )
);

CREATE TABLE IF NOT EXISTS capitalization_api.api_contract_versions (
    contract_name text NOT NULL,
    contract_version text NOT NULL,
    status text NOT NULL DEFAULT 'ACTIVE',
    documentation_reference text NOT NULL,
    authority_boundary text NOT NULL,
    effective_at timestamptz NOT NULL DEFAULT now(),
    retired_at timestamptz,
    PRIMARY KEY (contract_name, contract_version),
    CONSTRAINT capitalization_api_contract_status_chk CHECK (
        status IN ('DRAFT', 'ACTIVE', 'DEPRECATED', 'RETIRED')
    ),
    CONSTRAINT capitalization_api_contract_retired_chk CHECK (
        status <> 'RETIRED' OR retired_at IS NOT NULL
    )
);

INSERT INTO capitalization_api.api_contract_versions (
    contract_name,
    contract_version,
    status,
    documentation_reference,
    authority_boundary
) VALUES (
    'capitalization-public-directory',
    '1.0',
    'ACTIVE',
    'setc/capitalization/openapi.yaml',
    'Read-only public registry projection; no banking relationship, account, balance, custody, regulatory, or settlement authority is conferred.'
)
ON CONFLICT (contract_name, contract_version) DO UPDATE
SET status = EXCLUDED.status,
    documentation_reference = EXCLUDED.documentation_reference,
    authority_boundary = EXCLUDED.authority_boundary;

CREATE TABLE IF NOT EXISTS capitalization.public_projection_refresh_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refresh_reference text NOT NULL UNIQUE,
    refreshed_by_actor text NOT NULL,
    live_claim_gate_enabled boolean NOT NULL,
    directory_entry_count integer NOT NULL CHECK (directory_entry_count >= 0),
    evidence_backed_count integer NOT NULL CHECK (evidence_backed_count >= 0),
    verified_live_count integer NOT NULL CHECK (verified_live_count >= 0),
    refreshed_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION capitalization.refresh_public_network_projection(
    p_refreshed_by_actor text
)
RETURNS TABLE (
    directory_entry_count integer,
    evidence_backed_count integer,
    verified_live_count integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, capitalization, capitalization_api
AS $$
DECLARE
    v_gate_enabled boolean;
    v_total integer;
    v_evidence_backed integer;
    v_verified_live integer;
    v_refresh_reference text;
BEGIN
    IF p_refreshed_by_actor IS NULL OR length(btrim(p_refreshed_by_actor)) = 0 THEN
        RAISE EXCEPTION 'refreshed_by_actor is required'
            USING ERRCODE = '22023';
    END IF;

    SELECT capitalization.release_gate_enabled('PUBLIC_LIVE_NETWORK_CLAIMS')
      INTO v_gate_enabled;

    DELETE FROM capitalization_api.network_directory;

    INSERT INTO capitalization_api.network_directory (
        directory_entry_id,
        institution_reference,
        institution_display_name,
        institution_type,
        jurisdiction_code,
        region_code,
        sourceenergy_node_id,
        dominion_cube_id,
        relay_code,
        layer_number,
        operational_role,
        relationship_state,
        connectivity_status,
        verification_status,
        public_claim_status,
        relationship_label,
        connectivity_label,
        last_verified_at,
        disclosure,
        is_published,
        published_at,
        updated_at
    )
    SELECT
        n.sourceenergy_node_id,
        i.institution_reference,
        i.display_name,
        i.institution_type,
        i.jurisdiction_code,
        i.region_code,
        n.sourceenergy_node_id,
        n.dominion_cube_id,
        n.relay_code,
        n.layer_number,
        n.operational_role,
        COALESCE(r.relationship_state, 'TARGET'),
        n.connectivity_status,
        i.verification_status,
        CASE
            WHEN v_gate_enabled
                 AND r.relationship_state = 'LIVE'
                 AND n.connectivity_status = 'PRODUCTION'
                 AND n.environment = 'PRODUCTION'
                 AND n.node_status = 'ACTIVE'
                 AND i.verification_status = 'VERIFIED'
                 AND r.evidence_reference IS NOT NULL
                 AND n.evidence_reference IS NOT NULL
                 AND GREATEST(r.last_verified_at, n.last_verified_at, i.last_verified_at) IS NOT NULL
                THEN 'VERIFIED_LIVE'
            WHEN r.relationship_state IN (
                    'CONTRACTED', 'INTEGRATION_PENDING', 'INTEGRATED', 'LIVE'
                 )
                 AND r.evidence_reference IS NOT NULL
                THEN 'EVIDENCE_BACKED_NON_LIVE'
            ELSE 'REGISTRY_TARGET'
        END,
        CASE
            WHEN v_gate_enabled
                 AND r.relationship_state = 'LIVE'
                 AND n.connectivity_status = 'PRODUCTION'
                 AND n.environment = 'PRODUCTION'
                 AND n.node_status = 'ACTIVE'
                 AND i.verification_status = 'VERIFIED'
                 AND r.evidence_reference IS NOT NULL
                 AND n.evidence_reference IS NOT NULL
                THEN 'Verified live connection'
            WHEN r.relationship_state IN (
                    'CONTRACTED', 'INTEGRATION_PENDING', 'INTEGRATED', 'LIVE'
                 )
                 AND r.evidence_reference IS NOT NULL
                THEN 'Evidence-backed relationship; production status not publicly asserted'
            ELSE 'Registry target; no verified institutional relationship is asserted'
        END,
        CASE n.connectivity_status
            WHEN 'NOT_CONNECTED' THEN 'Not connected'
            WHEN 'SANDBOX' THEN 'Sandbox only'
            WHEN 'TEST' THEN 'Test only'
            WHEN 'CERTIFICATION' THEN 'Certification only'
            WHEN 'PRODUCTION' THEN
                CASE
                    WHEN v_gate_enabled
                         AND r.relationship_state = 'LIVE'
                         AND i.verification_status = 'VERIFIED'
                        THEN 'Verified production connection'
                    ELSE 'Production claim withheld pending governance authorization'
                END
            WHEN 'DEGRADED' THEN 'Degraded'
            WHEN 'OFFLINE' THEN 'Offline'
            ELSE 'Status unavailable'
        END,
        GREATEST(r.last_verified_at, n.last_verified_at, i.last_verified_at),
        'SourceEnergy registry metadata. Dominion Cube and Relay Code are SourceEnergy internal identifiers. No external banking relationship, custody authority, regulatory status, account access, or settlement connectivity is implied unless explicitly shown as a Verified live connection.',
        true,
        now(),
        now()
    FROM capitalization.financial_institutions i
    JOIN capitalization.network_nodes n
      ON n.institution_id = i.id
    LEFT JOIN capitalization.institution_relationships r
      ON r.institution_id = i.id
    WHERE i.public_display_enabled = true
      AND n.public_display_enabled = true
      AND i.operating_status NOT IN ('SUSPENDED', 'CLOSED')
      AND n.node_status <> 'RETIRED';

    SELECT count(*)::integer
      INTO v_total
      FROM capitalization_api.network_directory
     WHERE is_published = true;

    SELECT count(*)::integer
      INTO v_evidence_backed
      FROM capitalization_api.network_directory
     WHERE is_published = true
       AND public_claim_status IN ('EVIDENCE_BACKED_NON_LIVE', 'VERIFIED_LIVE');

    SELECT count(*)::integer
      INTO v_verified_live
      FROM capitalization_api.network_directory
     WHERE is_published = true
       AND public_claim_status = 'VERIFIED_LIVE';

    DELETE FROM capitalization_api.dashboard_metrics;

    INSERT INTO capitalization_api.dashboard_metrics (
        metric_code,
        metric_name,
        numeric_value,
        unit,
        measurement_kind,
        as_of,
        disclosure,
        is_published,
        updated_at
    ) VALUES
        (
            'registry_institution_count',
            'Published registry institutions',
            v_total,
            'institutions',
            'SYSTEM_DERIVED',
            now(),
            'Count of published SourceEnergy registry entries. It does not represent verified banking partners.',
            true,
            now()
        ),
        (
            'evidence_backed_relationship_count',
            'Evidence-backed institutional relationships',
            v_evidence_backed,
            'relationships',
            'SYSTEM_DERIVED',
            now(),
            'Count requires internal evidence but does not imply production connectivity.',
            true,
            now()
        ),
        (
            'verified_live_connection_count',
            'Verified live connections',
            v_verified_live,
            'connections',
            'SYSTEM_DERIVED',
            now(),
            'Count is nonzero only when contractual, verification, production-connectivity, and public-claim governance gates are all satisfied.',
            true,
            now()
        ),
        (
            'public_live_claim_gate',
            'Public live-network claim gate',
            CASE WHEN v_gate_enabled THEN 1 ELSE 0 END,
            'boolean',
            'SYSTEM_DERIVED',
            now(),
            'A value of 0 means no public production-connectivity claim is authorized.',
            true,
            now()
        );

    v_refresh_reference := format(
        'PUBLIC-PROJECTION-%s-%s',
        to_char(clock_timestamp(), 'YYYYMMDDHH24MISSMS'),
        substr(gen_random_uuid()::text, 1, 8)
    );

    INSERT INTO capitalization.public_projection_refresh_history (
        refresh_reference,
        refreshed_by_actor,
        live_claim_gate_enabled,
        directory_entry_count,
        evidence_backed_count,
        verified_live_count
    ) VALUES (
        v_refresh_reference,
        btrim(p_refreshed_by_actor),
        v_gate_enabled,
        v_total,
        v_evidence_backed,
        v_verified_live
    );

    RETURN QUERY SELECT v_total, v_evidence_backed, v_verified_live;
END;
$$;

DROP TRIGGER IF EXISTS capitalization_public_projection_refresh_append_only
    ON capitalization.public_projection_refresh_history;
CREATE TRIGGER capitalization_public_projection_refresh_append_only
BEFORE UPDATE OR DELETE ON capitalization.public_projection_refresh_history
FOR EACH ROW EXECUTE FUNCTION capitalization.prevent_mutation();

ALTER TABLE capitalization.public_projection_refresh_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE capitalization_api.network_directory ENABLE ROW LEVEL SECURITY;
ALTER TABLE capitalization_api.dashboard_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE capitalization_api.api_contract_versions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS capitalization_api_public_network_read
    ON capitalization_api.network_directory;
CREATE POLICY capitalization_api_public_network_read
ON capitalization_api.network_directory
FOR SELECT
TO anon, authenticated
USING (is_published = true);

DROP POLICY IF EXISTS capitalization_api_public_metrics_read
    ON capitalization_api.dashboard_metrics;
CREATE POLICY capitalization_api_public_metrics_read
ON capitalization_api.dashboard_metrics
FOR SELECT
TO anon, authenticated
USING (is_published = true);

DROP POLICY IF EXISTS capitalization_api_public_contracts_read
    ON capitalization_api.api_contract_versions;
CREATE POLICY capitalization_api_public_contracts_read
ON capitalization_api.api_contract_versions
FOR SELECT
TO anon, authenticated
USING (status IN ('ACTIVE', 'DEPRECATED'));

REVOKE ALL ON ALL TABLES IN SCHEMA capitalization_api FROM PUBLIC, anon, authenticated;
GRANT SELECT ON capitalization_api.network_directory TO anon, authenticated;
GRANT SELECT ON capitalization_api.dashboard_metrics TO anon, authenticated;
GRANT SELECT ON capitalization_api.api_contract_versions TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA capitalization_api TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA capitalization_api TO service_role;

REVOKE ALL ON capitalization.public_projection_refresh_history FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON capitalization.public_projection_refresh_history TO service_role;

REVOKE EXECUTE ON FUNCTION capitalization.refresh_public_network_projection(text)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION capitalization.refresh_public_network_projection(text)
    TO service_role;

COMMENT ON TABLE capitalization_api.network_directory IS
'Public-safe SourceEnergy institutional registry projection. Registry-target rows are not participating-bank claims. Financial and evidentiary data are excluded.';
COMMENT ON TABLE capitalization_api.dashboard_metrics IS
'Non-financial public system metrics only. Treasury balances, commitments, settlement amounts, and exposures are prohibited from this table.';
COMMENT ON FUNCTION capitalization.refresh_public_network_projection(text) IS
'Server-only projection refresh. A VERIFIED_LIVE label requires the public claim gate plus verified relationship, institution, and production node evidence.';

COMMIT;
