-- IBG-03 Payment Orchestration Control Plane
-- Internal payment intent and provider-state tracking only.
-- Provider-reported completion is not settlement finality; reconciliation belongs to IBG-06.

BEGIN;

CREATE TABLE IF NOT EXISTS capitalization.payment_instructions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    payment_reference text NOT NULL UNIQUE,
    idempotency_key text NOT NULL UNIQUE,
    source_treasury_account_id uuid NOT NULL
        REFERENCES capitalization.treasury_accounts(id) ON DELETE RESTRICT,
    destination_treasury_account_id uuid
        REFERENCES capitalization.treasury_accounts(id) ON DELETE RESTRICT,
    beneficiary_reference text,
    amount numeric(38, 12) NOT NULL CHECK (amount > 0),
    asset_code text NOT NULL,
    payment_purpose text NOT NULL,
    source_system text,
    source_record_reference text,
    payment_state text NOT NULL DEFAULT 'DRAFT',
    compliance_status text NOT NULL DEFAULT 'PENDING',
    required_approvals integer NOT NULL DEFAULT 2 CHECK (required_approvals >= 2),
    production_execution_enabled boolean NOT NULL DEFAULT false,
    route_institution_id uuid
        REFERENCES capitalization.financial_institutions(id) ON DELETE RESTRICT,
    route_node_id uuid
        REFERENCES capitalization.network_nodes(id) ON DELETE RESTRICT,
    route_type text,
    provider_reference text,
    provider_reported_status text,
    provider_reported_at timestamptz,
    expires_at timestamptz,
    requested_by_actor text NOT NULL,
    approved_ready_at timestamptz,
    submitted_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT capitalization_payment_state_chk CHECK (
        payment_state IN (
            'DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'READY', 'SUBMITTED',
            'ACCEPTED', 'PROCESSING', 'COMPLETED', 'REJECTED', 'CANCELLED',
            'FAILED', 'RETURNED', 'EXPIRED', 'ON_HOLD'
        )
    ),
    CONSTRAINT capitalization_payment_compliance_chk CHECK (
        compliance_status IN ('PENDING', 'CLEAR', 'REVIEW', 'ON_HOLD', 'REJECTED')
    ),
    CONSTRAINT capitalization_payment_route_type_chk CHECK (
        route_type IS NULL OR route_type IN (
            'SWIFT', 'LOCAL_CLEARING', 'ACH', 'SEPA', 'RTP', 'INTERNAL_PROVIDER', 'OTHER'
        )
    ),
    CONSTRAINT capitalization_payment_destination_chk CHECK (
        destination_treasury_account_id IS NOT NULL
        OR (beneficiary_reference IS NOT NULL AND length(btrim(beneficiary_reference)) > 0)
    ),
    CONSTRAINT capitalization_payment_provider_reference_chk CHECK (
        payment_state NOT IN ('SUBMITTED', 'ACCEPTED', 'PROCESSING', 'COMPLETED', 'RETURNED')
        OR (provider_reference IS NOT NULL AND length(btrim(provider_reference)) > 0)
    )
);

CREATE TABLE IF NOT EXISTS capitalization.payment_approvals (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    payment_instruction_id uuid NOT NULL
        REFERENCES capitalization.payment_instructions(id) ON DELETE RESTRICT,
    approver_actor text NOT NULL,
    approval_role text NOT NULL,
    approval_decision text NOT NULL,
    decision_reason text,
    evidence_reference text,
    decided_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (payment_instruction_id, approver_actor, approval_role),
    CONSTRAINT capitalization_payment_approval_role_chk CHECK (
        approval_role IN ('MAKER_REVIEW', 'CHECKER', 'TREASURY', 'COMPLIANCE', 'GOVERNANCE', 'OTHER')
    ),
    CONSTRAINT capitalization_payment_approval_decision_chk CHECK (
        approval_decision IN ('APPROVED', 'REJECTED', 'REVOKED')
    )
);

CREATE TABLE IF NOT EXISTS capitalization.payment_compliance_holds (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    payment_instruction_id uuid NOT NULL
        REFERENCES capitalization.payment_instructions(id) ON DELETE RESTRICT,
    hold_type text NOT NULL,
    hold_status text NOT NULL DEFAULT 'ACTIVE',
    reason text NOT NULL CHECK (length(btrim(reason)) > 0),
    evidence_reference text,
    imposed_by_actor text NOT NULL,
    imposed_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz,
    released_by_actor text,
    released_at timestamptz,
    CONSTRAINT capitalization_payment_hold_type_chk CHECK (
        hold_type IN ('KYC_KYB', 'AML', 'SANCTIONS', 'FRAUD', 'LIMIT', 'DOCUMENTATION', 'MANUAL_REVIEW', 'OTHER')
    ),
    CONSTRAINT capitalization_payment_hold_status_chk CHECK (
        hold_status IN ('ACTIVE', 'RELEASED', 'EXPIRED')
    )
);

CREATE TABLE IF NOT EXISTS capitalization.payment_state_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_instruction_id uuid NOT NULL
        REFERENCES capitalization.payment_instructions(id) ON DELETE RESTRICT,
    prior_state text,
    new_state text NOT NULL,
    prior_record jsonb NOT NULL,
    new_record jsonb NOT NULL,
    changed_by_actor text,
    changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION capitalization.validate_payment_state_transition()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, capitalization
AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.payment_state IS DISTINCT FROM NEW.payment_state THEN
        IF OLD.payment_state IN ('COMPLETED', 'REJECTED', 'CANCELLED', 'FAILED', 'RETURNED', 'EXPIRED') THEN
            RAISE EXCEPTION 'terminal payment state cannot transition'
                USING ERRCODE = '23514';
        END IF;

        IF NOT (
            (OLD.payment_state = 'DRAFT' AND NEW.payment_state IN ('PENDING_APPROVAL', 'CANCELLED')) OR
            (OLD.payment_state = 'PENDING_APPROVAL' AND NEW.payment_state IN ('APPROVED', 'REJECTED', 'ON_HOLD', 'CANCELLED', 'EXPIRED')) OR
            (OLD.payment_state = 'ON_HOLD' AND NEW.payment_state IN ('PENDING_APPROVAL', 'REJECTED', 'CANCELLED', 'EXPIRED')) OR
            (OLD.payment_state = 'APPROVED' AND NEW.payment_state IN ('READY', 'ON_HOLD', 'CANCELLED', 'EXPIRED')) OR
            (OLD.payment_state = 'READY' AND NEW.payment_state IN ('SUBMITTED', 'ON_HOLD', 'CANCELLED', 'EXPIRED')) OR
            (OLD.payment_state = 'SUBMITTED' AND NEW.payment_state IN ('ACCEPTED', 'PROCESSING', 'FAILED', 'RETURNED')) OR
            (OLD.payment_state = 'ACCEPTED' AND NEW.payment_state IN ('PROCESSING', 'COMPLETED', 'FAILED', 'RETURNED')) OR
            (OLD.payment_state = 'PROCESSING' AND NEW.payment_state IN ('COMPLETED', 'FAILED', 'RETURNED'))
        ) THEN
            RAISE EXCEPTION 'invalid payment state transition: % -> %', OLD.payment_state, NEW.payment_state
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION capitalization.validate_payment_execution_gate()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, capitalization
AS $$
DECLARE
    v_account_status text;
    v_account_verification text;
    v_account_eligibility text;
    v_custodian_id uuid;
    v_institution_verification text;
    v_institution_operating text;
    v_approval_count integer;
BEGIN
    IF NEW.payment_state IN ('APPROVED', 'READY', 'SUBMITTED', 'ACCEPTED', 'PROCESSING', 'COMPLETED') THEN
        SELECT count(*)
          INTO v_approval_count
          FROM capitalization.payment_approvals pa
         WHERE pa.payment_instruction_id = NEW.id
           AND pa.approval_decision = 'APPROVED';

        IF v_approval_count < NEW.required_approvals THEN
            RAISE EXCEPTION 'payment requires % approvals; only % recorded', NEW.required_approvals, v_approval_count
                USING ERRCODE = '23514';
        END IF;

        IF NEW.compliance_status <> 'CLEAR' THEN
            RAISE EXCEPTION 'payment cannot advance while compliance status is not CLEAR'
                USING ERRCODE = '23514';
        END IF;

        IF EXISTS (
            SELECT 1
              FROM capitalization.payment_compliance_holds h
             WHERE h.payment_instruction_id = NEW.id
               AND h.hold_status = 'ACTIVE'
               AND (h.expires_at IS NULL OR h.expires_at > now())
        ) THEN
            RAISE EXCEPTION 'payment cannot advance while an active compliance hold exists'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    IF NEW.payment_state IN ('READY', 'SUBMITTED', 'ACCEPTED', 'PROCESSING', 'COMPLETED') THEN
        SELECT account_status, verification_status, operational_eligibility, custodian_institution_id
          INTO v_account_status, v_account_verification, v_account_eligibility, v_custodian_id
          FROM capitalization.treasury_accounts
         WHERE id = NEW.source_treasury_account_id;

        IF v_account_status IS DISTINCT FROM 'ACTIVE'
           OR v_account_verification IS DISTINCT FROM 'VERIFIED'
           OR v_account_eligibility IS DISTINCT FROM 'PRODUCTION_ELIGIBLE' THEN
            RAISE EXCEPTION 'payment route requires ACTIVE, VERIFIED, PRODUCTION_ELIGIBLE source account'
                USING ERRCODE = '23514';
        END IF;

        IF v_custodian_id IS NULL THEN
            RAISE EXCEPTION 'payment route requires a custodian institution'
                USING ERRCODE = '23514';
        END IF;

        SELECT verification_status, operating_status
          INTO v_institution_verification, v_institution_operating
          FROM capitalization.financial_institutions
         WHERE id = v_custodian_id;

        IF v_institution_verification IS DISTINCT FROM 'VERIFIED'
           OR v_institution_operating NOT IN ('APPROVED', 'ACTIVE') THEN
            RAISE EXCEPTION 'payment route requires VERIFIED and approved/active custodian institution'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    IF NEW.payment_state IN ('SUBMITTED', 'ACCEPTED', 'PROCESSING', 'COMPLETED') THEN
        IF NEW.production_execution_enabled IS NOT TRUE THEN
            RAISE EXCEPTION 'production execution is disabled for this payment instruction'
                USING ERRCODE = '23514';
        END IF;

        IF NEW.route_institution_id IS NULL OR NEW.route_node_id IS NULL THEN
            RAISE EXCEPTION 'submitted payment requires explicit institution and network route'
                USING ERRCODE = '23514';
        END IF;

        IF NOT EXISTS (
            SELECT 1
              FROM capitalization.financial_institutions fi
              JOIN capitalization.network_nodes nn ON nn.institution_id = fi.id
             WHERE fi.id = NEW.route_institution_id
               AND fi.verification_status = 'VERIFIED'
               AND fi.operating_status IN ('APPROVED', 'ACTIVE')
               AND nn.id = NEW.route_node_id
               AND nn.connectivity_status = 'PRODUCTION'
               AND nn.environment = 'PRODUCTION'
               AND nn.node_status = 'ACTIVE'
               AND nn.evidence_reference IS NOT NULL
               AND nn.last_verified_at IS NOT NULL
        ) THEN
            RAISE EXCEPTION 'submitted payment requires evidence-backed production route'
                USING ERRCODE = '23514';
        END IF;
    END IF;

    IF NEW.payment_state = 'COMPLETED' AND NEW.completed_at IS NULL THEN
        NEW.completed_at := now();
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION capitalization.capture_payment_state_history()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, capitalization
AS $$
BEGIN
    IF OLD.payment_state IS DISTINCT FROM NEW.payment_state
       OR OLD.compliance_status IS DISTINCT FROM NEW.compliance_status
       OR OLD.provider_reported_status IS DISTINCT FROM NEW.provider_reported_status THEN
        INSERT INTO capitalization.payment_state_history (
            payment_instruction_id,
            prior_state,
            new_state,
            prior_record,
            new_record,
            changed_by_actor
        ) VALUES (
            NEW.id,
            OLD.payment_state,
            NEW.payment_state,
            to_jsonb(OLD),
            to_jsonb(NEW),
            NEW.requested_by_actor
        );
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS capitalization_payment_instructions_updated_at
    ON capitalization.payment_instructions;
CREATE TRIGGER capitalization_payment_instructions_updated_at
BEFORE UPDATE ON capitalization.payment_instructions
FOR EACH ROW EXECUTE FUNCTION capitalization.set_updated_at();

DROP TRIGGER IF EXISTS capitalization_payment_state_transition_validation
    ON capitalization.payment_instructions;
CREATE TRIGGER capitalization_payment_state_transition_validation
BEFORE UPDATE ON capitalization.payment_instructions
FOR EACH ROW EXECUTE FUNCTION capitalization.validate_payment_state_transition();

DROP TRIGGER IF EXISTS capitalization_payment_execution_validation
    ON capitalization.payment_instructions;
CREATE TRIGGER capitalization_payment_execution_validation
BEFORE INSERT OR UPDATE ON capitalization.payment_instructions
FOR EACH ROW EXECUTE FUNCTION capitalization.validate_payment_execution_gate();

DROP TRIGGER IF EXISTS capitalization_payment_state_history_capture
    ON capitalization.payment_instructions;
CREATE TRIGGER capitalization_payment_state_history_capture
AFTER UPDATE ON capitalization.payment_instructions
FOR EACH ROW EXECUTE FUNCTION capitalization.capture_payment_state_history();

DROP TRIGGER IF EXISTS capitalization_payment_state_history_append_only
    ON capitalization.payment_state_history;
CREATE TRIGGER capitalization_payment_state_history_append_only
BEFORE UPDATE OR DELETE ON capitalization.payment_state_history
FOR EACH ROW EXECUTE FUNCTION capitalization.prevent_mutation();

DROP TRIGGER IF EXISTS capitalization_payment_approvals_append_only
    ON capitalization.payment_approvals;
CREATE TRIGGER capitalization_payment_approvals_append_only
BEFORE UPDATE OR DELETE ON capitalization.payment_approvals
FOR EACH ROW EXECUTE FUNCTION capitalization.prevent_mutation();

CREATE INDEX IF NOT EXISTS capitalization_payment_source_state_idx
    ON capitalization.payment_instructions (source_treasury_account_id, payment_state, created_at DESC);
CREATE INDEX IF NOT EXISTS capitalization_payment_route_state_idx
    ON capitalization.payment_instructions (route_institution_id, route_node_id, payment_state);
CREATE INDEX IF NOT EXISTS capitalization_payment_approvals_instruction_idx
    ON capitalization.payment_approvals (payment_instruction_id, approval_decision);
CREATE INDEX IF NOT EXISTS capitalization_payment_holds_instruction_idx
    ON capitalization.payment_compliance_holds (payment_instruction_id, hold_status);
CREATE INDEX IF NOT EXISTS capitalization_payment_history_instruction_idx
    ON capitalization.payment_state_history (payment_instruction_id, changed_at DESC);

ALTER TABLE capitalization.payment_instructions ENABLE ROW LEVEL SECURITY;
ALTER TABLE capitalization.payment_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE capitalization.payment_compliance_holds ENABLE ROW LEVEL SECURITY;
ALTER TABLE capitalization.payment_state_history ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON capitalization.payment_instructions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON capitalization.payment_approvals FROM PUBLIC, anon, authenticated;
REVOKE ALL ON capitalization.payment_compliance_holds FROM PUBLIC, anon, authenticated;
REVOKE ALL ON capitalization.payment_state_history FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON capitalization.payment_instructions TO service_role;
GRANT SELECT, INSERT ON capitalization.payment_approvals TO service_role;
GRANT SELECT, INSERT, UPDATE ON capitalization.payment_compliance_holds TO service_role;
GRANT SELECT, INSERT ON capitalization.payment_state_history TO service_role;

CREATE OR REPLACE VIEW capitalization_api.payment_orchestration AS
SELECT
    pi.payment_reference,
    pi.asset_code,
    pi.amount,
    pi.payment_purpose,
    pi.payment_state,
    pi.compliance_status,
    pi.required_approvals,
    (
        SELECT count(*)
          FROM capitalization.payment_approvals pa
         WHERE pa.payment_instruction_id = pi.id
           AND pa.approval_decision = 'APPROVED'
    ) AS recorded_approvals,
    pi.production_execution_enabled,
    fi.institution_reference AS route_institution_reference,
    pi.route_type,
    pi.provider_reported_status,
    pi.provider_reported_at,
    pi.created_at,
    pi.updated_at,
    CASE
        WHEN pi.payment_state = 'COMPLETED'
            THEN 'Provider-reported completion only; IBG-06 reconciliation is required for settlement finality.'
        ELSE 'Internal payment-orchestration state; no external settlement finality implied.'
    END AS disclosure
FROM capitalization.payment_instructions pi
LEFT JOIN capitalization.financial_institutions fi
  ON fi.id = pi.route_institution_id;

REVOKE ALL ON capitalization_api.payment_orchestration FROM PUBLIC, anon;
GRANT SELECT ON capitalization_api.payment_orchestration TO authenticated, service_role;

COMMENT ON TABLE capitalization.payment_instructions IS
'IBG-03 payment intent and provider-state control plane. Internal state never proves external bank settlement finality.';
COMMENT ON TABLE capitalization.payment_approvals IS
'Append-only maker/checker and governance approval evidence for payment instructions.';
COMMENT ON VIEW capitalization_api.payment_orchestration IS
'Authenticated read-safe payment projection excluding credentials and sensitive account identifiers. COMPLETED is provider-reported, not IBG-06 settlement finality.';

COMMIT;
