-- IBG-07 Production Connectivity & Institutional Certification
-- Certification metadata only. Secrets are prohibited. No row itself enables external production connectivity.
BEGIN;

CREATE TABLE IF NOT EXISTS capitalization.certification_programs (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), certification_reference text NOT NULL UNIQUE,
 institution_id uuid NOT NULL REFERENCES capitalization.financial_institutions(id) ON DELETE RESTRICT,
 certification_scope text NOT NULL, environment text NOT NULL DEFAULT 'DUE_DILIGENCE', status text NOT NULL DEFAULT 'OPEN',
 governance_reference text, opened_by_actor text NOT NULL, opened_at timestamptz NOT NULL DEFAULT now(), certified_at timestamptz,
 suspended_at timestamptz, revoked_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT certification_environment_chk CHECK(environment IN ('DISCOVERY','DUE_DILIGENCE','SANDBOX','UAT','PRODUCTION_CANDIDATE','PRODUCTION_CERTIFIED')),
 CONSTRAINT certification_status_chk CHECK(status IN ('OPEN','IN_REVIEW','BLOCKED','APPROVED','SUSPENDED','REVOKED','EXPIRED'))
);

CREATE TABLE IF NOT EXISTS capitalization.certification_evidence (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), certification_program_id uuid NOT NULL REFERENCES capitalization.certification_programs(id) ON DELETE RESTRICT,
 domain text NOT NULL, evidence_type text NOT NULL, authoritative_source text NOT NULL, evidence_reference text NOT NULL,
 issued_or_observed_at timestamptz NOT NULL, expires_at timestamptz, verification_status text NOT NULL DEFAULT 'PENDING',
 verified_by_actor text, verified_at timestamptz, notes text, created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT certification_domain_chk CHECK(domain IN ('LEGAL_ENTITY','REGULATORY','COMMERCIAL_RELATIONSHIP','ACCOUNT_CUSTODY','TECHNICAL_ENDPOINT','PAYMENT_ROUTE','TREASURY_LIQUIDITY','TRADE_FINANCE','SETTLEMENT_FINALITY','OPERATIONS')),
 CONSTRAINT certification_evidence_status_chk CHECK(verification_status IN ('PENDING','VERIFIED','REJECTED','EXPIRED','SUPERSEDED')),
 CONSTRAINT certification_verified_chk CHECK(verification_status<>'VERIFIED' OR (verified_by_actor IS NOT NULL AND verified_at IS NOT NULL)),
 CONSTRAINT certification_expiry_chk CHECK(expires_at IS NULL OR expires_at>issued_or_observed_at)
);

CREATE TABLE IF NOT EXISTS capitalization.certification_exceptions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), certification_program_id uuid NOT NULL REFERENCES capitalization.certification_programs(id) ON DELETE RESTRICT,
 exception_code text NOT NULL, severity text NOT NULL, description text NOT NULL, status text NOT NULL DEFAULT 'OPEN',
 remediation_reference text, opened_by_actor text NOT NULL, opened_at timestamptz NOT NULL DEFAULT now(), resolved_by_actor text, resolved_at timestamptz,
 CONSTRAINT certification_exception_severity_chk CHECK(severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
 CONSTRAINT certification_exception_status_chk CHECK(status IN ('OPEN','REMEDIATING','RESOLVED','ACCEPTED','CLOSED')),
 CONSTRAINT certification_exception_resolution_chk CHECK(status NOT IN ('RESOLVED','CLOSED') OR (resolved_by_actor IS NOT NULL AND resolved_at IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS capitalization.certification_approvals (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), certification_program_id uuid NOT NULL REFERENCES capitalization.certification_programs(id) ON DELETE RESTRICT,
 approval_role text NOT NULL, approver_actor text NOT NULL, decision text NOT NULL, governance_reference text NOT NULL,
 decided_at timestamptz NOT NULL DEFAULT now(), UNIQUE(certification_program_id,approval_role,approver_actor),
 CONSTRAINT certification_approval_role_chk CHECK(approval_role IN ('MAKER','CHECKER','COMPLIANCE','SECURITY','OPERATIONS','GOVERNANCE')),
 CONSTRAINT certification_approval_decision_chk CHECK(decision IN ('APPROVED','REJECTED','REVOKED'))
);

CREATE TABLE IF NOT EXISTS capitalization.certification_route_bindings (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), certification_program_id uuid NOT NULL REFERENCES capitalization.certification_programs(id) ON DELETE RESTRICT,
 treasury_account_id uuid REFERENCES capitalization.treasury_accounts(id) ON DELETE RESTRICT,
 payment_network_node_id uuid REFERENCES capitalization.payment_network_nodes(id) ON DELETE RESTRICT,
 asset_code text, route_scope text NOT NULL, binding_status text NOT NULL DEFAULT 'CANDIDATE', evidence_reference text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT certification_binding_status_chk CHECK(binding_status IN ('CANDIDATE','UAT_VERIFIED','PRODUCTION_CERTIFIED','SUSPENDED','REVOKED'))
);

CREATE TABLE IF NOT EXISTS capitalization.certification_history (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, certification_program_id uuid NOT NULL REFERENCES capitalization.certification_programs(id) ON DELETE RESTRICT,
 event_type text NOT NULL, prior_record jsonb, new_record jsonb NOT NULL, changed_by_actor text, changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION capitalization.validate_production_certification()
RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,capitalization AS $$
DECLARE required_domains integer; approvals integer; BEGIN
 IF NEW.environment='PRODUCTION_CERTIFIED' OR NEW.status='APPROVED' THEN
  SELECT count(DISTINCT domain) INTO required_domains FROM capitalization.certification_evidence e
   WHERE e.certification_program_id=NEW.id AND e.verification_status='VERIFIED' AND (e.expires_at IS NULL OR e.expires_at>now())
   AND e.domain IN ('LEGAL_ENTITY','REGULATORY','COMMERCIAL_RELATIONSHIP','ACCOUNT_CUSTODY','TECHNICAL_ENDPOINT','PAYMENT_ROUTE','TREASURY_LIQUIDITY','SETTLEMENT_FINALITY','OPERATIONS');
  IF required_domains<9 THEN RAISE EXCEPTION 'production certification requires all mandatory verified evidence domains' USING ERRCODE='23514'; END IF;
  IF EXISTS(SELECT 1 FROM capitalization.certification_exceptions x WHERE x.certification_program_id=NEW.id AND x.severity='CRITICAL' AND x.status NOT IN ('RESOLVED','CLOSED')) THEN RAISE EXCEPTION 'critical certification exception remains unresolved' USING ERRCODE='23514'; END IF;
  SELECT count(DISTINCT approval_role) INTO approvals FROM capitalization.certification_approvals a WHERE a.certification_program_id=NEW.id AND a.decision='APPROVED' AND a.approval_role IN ('CHECKER','COMPLIANCE','SECURITY','OPERATIONS','GOVERNANCE');
  IF approvals<5 THEN RAISE EXCEPTION 'production certification requires checker, compliance, security, operations and governance approvals' USING ERRCODE='23514'; END IF;
  IF NEW.governance_reference IS NULL THEN RAISE EXCEPTION 'production certification requires governance reference' USING ERRCODE='23514'; END IF;
  NEW.certified_at:=COALESCE(NEW.certified_at,now());
 END IF; RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION capitalization.capture_certification_history()
RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,capitalization AS $$ BEGIN
 IF OLD.environment IS DISTINCT FROM NEW.environment OR OLD.status IS DISTINCT FROM NEW.status THEN
  INSERT INTO capitalization.certification_history(certification_program_id,event_type,prior_record,new_record,changed_by_actor)
  VALUES(NEW.id,'CERTIFICATION_STATE_CHANGED',to_jsonb(OLD),to_jsonb(NEW),NEW.opened_by_actor); END IF; RETURN NEW; END; $$;

CREATE TRIGGER capitalization_certification_updated_at BEFORE UPDATE ON capitalization.certification_programs FOR EACH ROW EXECUTE FUNCTION capitalization.set_updated_at();
CREATE TRIGGER capitalization_certification_validation BEFORE INSERT OR UPDATE ON capitalization.certification_programs FOR EACH ROW EXECUTE FUNCTION capitalization.validate_production_certification();
CREATE TRIGGER capitalization_certification_history AFTER UPDATE ON capitalization.certification_programs FOR EACH ROW EXECUTE FUNCTION capitalization.capture_certification_history();
CREATE TRIGGER capitalization_certification_approvals_append_only BEFORE UPDATE OR DELETE ON capitalization.certification_approvals FOR EACH ROW EXECUTE FUNCTION capitalization.prevent_mutation();
CREATE TRIGGER capitalization_certification_history_append_only BEFORE UPDATE OR DELETE ON capitalization.certification_history FOR EACH ROW EXECUTE FUNCTION capitalization.prevent_mutation();

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['certification_programs','certification_evidence','certification_exceptions','certification_approvals','certification_route_bindings','certification_history'] LOOP EXECUTE format('ALTER TABLE capitalization.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('REVOKE ALL ON capitalization.%I FROM PUBLIC, anon, authenticated',t); EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON capitalization.%I TO service_role',t); END LOOP; END $$;
REVOKE UPDATE,DELETE ON capitalization.certification_approvals FROM service_role;
REVOKE UPDATE,DELETE ON capitalization.certification_history FROM service_role;

CREATE OR REPLACE VIEW capitalization_api.production_certifications AS
SELECT p.certification_reference,fi.institution_reference,p.certification_scope,p.environment,p.status,p.certified_at,p.suspended_at,p.revoked_at,
 'Certification governance state only. This projection does not itself prove a live bank relationship, account, rail, endpoint, available funds, payment authority, custody, trade-finance undertaking, or settlement finality.'::text disclosure
FROM capitalization.certification_programs p JOIN capitalization.financial_institutions fi ON fi.id=p.institution_id;
REVOKE ALL ON capitalization_api.production_certifications FROM PUBLIC,anon; GRANT SELECT ON capitalization_api.production_certifications TO authenticated,service_role;

COMMENT ON TABLE capitalization.certification_evidence IS 'Evidence metadata only. Secret values and credential payloads are prohibited.';
COMMENT ON TABLE capitalization.certification_route_bindings IS 'A binding record cannot enable production routing; production execution remains subject to IBG-01 through IBG-06 controls.';
COMMIT;
