alter table public.set_sourcecube_labs add column if not exists cohort_class text not null default 'accelerator';
alter table public.set_sourcecube_labs add column if not exists governance_status text not null default 'operational';
create table if not exists public.set_entity_governance_relationships (
 id bigint generated by default as identity primary key,
 parent_entity_name text not null,
 child_entity_name text not null,
 relationship_type text not null,
 evidence_status text not null default 'directed / evidence pending',
 evidence_reference text,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(parent_entity_name,child_entity_name,relationship_type)
);
comment on table public.set_entity_governance_relationships is 'Governance/holding relationship register. Directed relationships remain evidence-pending until supporting legal instruments are verified.';
