create table if not exists sourcecubes.setc_027_claim_decomposition (
  concept_id text primary key,
  working_title text not null,
  claim_lane text not null,
  technical_mechanism text not null,
  source_sections text not null,
  novelty_risk text not null,
  family_treatment text not null,
  priority text not null,
  status text not null default 'COUNSEL_REVIEW_REQUIRED',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into sourcecubes.setc_027_claim_decomposition(concept_id,working_title,claim_lane,technical_mechanism,source_sections,novelty_risk,family_treatment,priority,notes) values
('AI-AUTH-01','Machine-Enforced Intelligence Authority Classification','SYSTEM_METHOD','Attach an authority class to material intelligence outputs and enforce separation among SOURCE, LEDGER_VERIFIED, DERIVED, MODEL_INFERRED, HUMAN_REVIEWED and GOVERNANCE_APPROVED states.','Foundational Rule; §§4,35-39,65,67; Architecture Decision','MEDIUM: authority labels/governance concepts exist broadly; patent significance depends on concrete machine state model and enforcement interfaces.','CORE_DISTINCT_FAMILY_CANDIDATE','P1','Focus claims on technical state transitions and enforcement, not abstract governance labels.'),
('AI-AUTH-02','No-Authority-by-Model-Inference Control Gate','SYSTEM_METHOD','Prevent model inference or risk score from directly mutating authoritative identity, legal, financial, compliance, validator, treasury, ownership or root-trust state absent a governed promotion event.','Foundational Rule; §§23,25,30-31,36-39,67 V15; Acceptance Scenario','MEDIUM: human-in-loop controls are known; potential distinctiveness is generalized machine-enforced prohibition across authoritative ledger/control domains.','CORE_DISTINCT_FAMILY_CANDIDATE','P1','Candidate independent claim if implementation supplies explicit policy engine, authority-state metadata and blocked mutation path.'),
('AI-AUTH-03','Governed Promotion of Derived Intelligence to Authoritative Decision','SYSTEM_METHOD','Promote derived/model-inferred output only through an explicit review/approval transition that records reviewer or policy authority, evidence, rationale and resulting authorized action.','§§4-5,35-38,57,67; Exit Criteria','MEDIUM-HIGH: approval workflows are common; novelty requires specific cryptographic/ledger state-transition mechanism and lineage binding.','DEPENDENT_OR_COMBINATION_CLAIM','P1','Likely combine with AI-AUTH-01/02 rather than standalone family.'),
('AI-LIN-01','End-to-End Model-Assisted Decision Evidence Lineage','SYSTEM_METHOD_CRM','Machine-readable chain from source data through transformations/features, model/version, output, explanation, human/policy review, final authority decision and resulting SETC transaction/action.','§§6-10,22,35,56-57,66-67; Acceptance Scenario','MEDIUM: ML lineage is established art; potential novelty is binding lineage to governed authoritative transaction state.','CORE_OR_CONTINUATION_CANDIDATE','P1','Prior-art search should emphasize model lineage tied to blockchain transaction authorization and governance state.'),
('AI-AGENT-01','Authority-Scoped AI Agent Transaction Preparation and Execution','SYSTEM_METHOD','AI agents operate under registered machine identities and scoped tool permissions; read/propose/approve/sign/execute are distinct capabilities, with high-impact execution forced through human-equivalent authorization and evidence controls.','§§43,46,67 V12; Architecture Decision','HIGH: agent permissions/least privilege are active prior art areas. Distinctiveness requires SETC-specific machine-identity plus transaction-state enforcement.','CONTINUATION_OR_COMBINATION_CANDIDATE','P2','Do not claim generic tool permissions or agent authorization.'),
('AI-GRD-01','Authority-Aware Grounded Generative Output Control','SYSTEM_METHOD','Ground material generated outputs in traceable authoritative references while labeling unsupported content as inference/uncertainty and preventing fabricated ledger/transaction/approval/reserve/audit facts.','§§40-45,67 V13','HIGH: RAG grounding and hallucination controls are crowded art.','SUPPORTING_CLAIM_OR_TRADE_SECRET','P3','Preserve implementation details; avoid standalone family absent unusual enforcement mechanism.'),
('AI-RISK-01','Authority-Bounded Risk Score Record','DATA_STRUCTURE_METHOD','Risk score record binds model/version, input snapshot/lineage, contributing factors, confidence, reason codes, authority class, review requirement, expiration and decision reference, while preventing score from becoming proof of authoritative conclusions.','§§22-25,28','HIGH: risk scoring and model cards are mature art.','DEPENDENT_CLAIM','P2','Useful structured dependent claim if tied to AI-AUTH-02 enforcement.'),
('AI-MON-01','Governed Model Drift-to-Restriction State Transition','SYSTEM_METHOD','Evidence-based drift or incident detection triggers versioned warning/review/restriction/rollback/retirement states and fallback without fabricating missing intelligence or silently approving outcomes.','§§50-55,67 V10-V11','HIGH: MLOps monitoring and rollback are mature art.','DEPENDENT_OR_TRADE_SECRET','P3','Treat as supporting claims/know-how unless implementation reveals unique ledger-bound control.'),
('AI-EXP-01','Authority-Class-Preserving Intelligence Export','DATA_STRUCTURE_METHOD','Export intelligence with requester, purpose, authorized scope, source lineage, privacy class, model/metric versions, generation time and integrity hash while preserving authority classification.','§§60,66','MEDIUM-HIGH: provenance exports known; possible value in authority-class preservation and integrity binding.','DEPENDENT_CLAIM','P2','Potential claim under AI-AUTH-01/AI-LIN-01.'),
('AI-DEC-01','Decision-Support Record Separating Facts, Inference and Final Authority','DATA_STRUCTURE_SYSTEM','Decision record explicitly links authoritative facts, derived analytics, model outputs, options, risk, uncertainty, reviewer, final decision, decision authority and rationale without conflating the classes.','§§35-39,65','MEDIUM: decision provenance systems exist; technical distinctiveness depends on enforced typed state and mutation boundaries.','CORE_OR_DEPENDENT_CANDIDATE','P1','Evaluate as independent data-structure/system claim or dependent claim on authority-class engine.')
on conflict (concept_id) do update set working_title=excluded.working_title,claim_lane=excluded.claim_lane,technical_mechanism=excluded.technical_mechanism,source_sections=excluded.source_sections,novelty_risk=excluded.novelty_risk,family_treatment=excluded.family_treatment,priority=excluded.priority,notes=excluded.notes,updated_at=now();

update sourcecubes.setc_distinct_subfamily_review
set preliminary_review_status='CLAIM_DECOMPOSITION_COMPLETE_PENDING_PRIOR_ART_AND_IMPLEMENTATION_EVIDENCE',
    legacy_49_slot_recommendation='HOLD_FOR_P1_PRIOR_ART_AND_TECHNICAL_IMPLEMENTATION_EVIDENCE',
    required_next_evidence='Prior-art search focused on machine-enforced derived-vs-authoritative state separation; implementation/code/schema evidence for authority-class state transitions and blocked mutation paths; claim-specific inventor contribution matrix; assignment/chain-of-title evidence.',
    updated_at=now()
where setc_id='SETC-027';

comment on table sourcecubes.setc_027_claim_decomposition is 'Pre-counsel technical claim decomposition for SETC-027. Working concepts are not patent claims and do not establish novelty, patentability, inventorship, ownership, or freedom to operate.';
