create table if not exists energy.financial_models (
  financial_model_id uuid primary key default gen_random_uuid(),
  model_code text not null unique check (model_code ~ '^[A-Z0-9_-]{3,96}$'),
  project_id uuid references energy.projects(project_id) on delete restrict,
  asset_id uuid references energy.assets(asset_id) on delete restrict,
  model_type text not null check (model_type in ('PROJECT_FINANCE','ASSET_VALUATION','PPA_ECONOMICS','STORAGE_ECONOMICS','DER_ECONOMICS','FUEL_ECONOMICS','OTHER')),
  model_state text not null default 'DRAFT' check (model_state in ('DRAFT','IN_REVIEW','REFERENCE','VALIDATED_REFERENCE','APPROVED_REFERENCE','SUPERSEDED','ARCHIVED')),
  currency_code text not null default 'USD' check (currency_code ~ '^[A-Z]{3}$'),
  base_date date,
  verification_state text not null default 'UNVERIFIED' check (verification_state in ('UNVERIFIED','PENDING_VERIFICATION','REFERENCE_VERIFIED','VERIFIED','DISPUTED','ARCHIVED')),
  evidence_reference text,
  assumptions_version text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (project_id is not null or asset_id is not null)
);
comment on table energy.financial_models is 'Energy-specific project economics and valuation models. A model or approved-reference state is not a financing commitment, fair-value opinion, investment recommendation, booked asset value, or proof of available funds.';

create table if not exists energy.financial_assumptions (
  assumption_id uuid primary key default gen_random_uuid(),
  financial_model_id uuid not null references energy.financial_models(financial_model_id) on delete cascade,
  assumption_type text not null check (assumption_type in ('CAPEX','OPEX_FIXED','OPEX_VARIABLE','ENERGY_PRICE','CAPACITY_PRICE','REC_PRICE','FUEL_PRICE','ESCALATION','DEGRADATION','AVAILABILITY','CAPACITY_FACTOR','TAX_RATE_REFERENCE','DISCOUNT_RATE','DEBT_RATE_REFERENCE','TENOR_REFERENCE','DSCR_TARGET_REFERENCE','OTHER')),
  assumption_value_numeric numeric,
  assumption_value_text text,
  unit text,
  source_class text not null default 'INTERNAL_ASSUMPTION' check (source_class in ('INTERNAL_ASSUMPTION','CONTRACT_REFERENCE','MARKET_REFERENCE','VENDOR_QUOTE_REFERENCE','ENGINEERING_REFERENCE','REGULATORY_REFERENCE','THIRD_PARTY_REFERENCE','OTHER')),
  verification_state text not null default 'UNVERIFIED' check (verification_state in ('UNVERIFIED','PENDING_VERIFICATION','REFERENCE_VERIFIED','VERIFIED','DISPUTED','ARCHIVED')),
  evidence_reference text,
  effective_from date,
  effective_to date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (assumption_value_numeric is not null or assumption_value_text is not null),
  check (effective_to is null or effective_from is null or effective_to >= effective_from)
);

create table if not exists energy.cash_flow_projections (
  cash_flow_id bigint generated by default as identity primary key,
  financial_model_id uuid not null references energy.financial_models(financial_model_id) on delete cascade,
  period_start date not null,
  period_end date not null,
  flow_type text not null check (flow_type in ('CAPEX','REVENUE_ENERGY','REVENUE_CAPACITY','REVENUE_REC_REFERENCE','REVENUE_OTHER','OPEX_FIXED','OPEX_VARIABLE','FUEL_COST','DEBT_SERVICE_REFERENCE','TAX_REFERENCE','WORKING_CAPITAL','OTHER')),
  amount numeric not null,
  currency_code text not null default 'USD' check (currency_code ~ '^[A-Z]{3}$'),
  projection_kind text not null default 'MODELED' check (projection_kind in ('MODELED','FORECAST','CONTRACT_REFERENCE','ACTUAL_REFERENCE','CORRECTED_REFERENCE')),
  verification_state text not null default 'UNVERIFIED' check (verification_state in ('UNVERIFIED','PENDING_VERIFICATION','REFERENCE_VERIFIED','VERIFIED','DISPUTED','ARCHIVED')),
  evidence_reference text,
  external_reference text,
  created_at timestamptz not null default now(),
  check (period_end >= period_start),
  check ((projection_kind in ('MODELED','FORECAST')) or evidence_reference is not null)
);
comment on table energy.cash_flow_projections is 'Modeled or reference cash-flow records. ACTUAL_REFERENCE requires evidence but remains a reference to authoritative accounting/settlement systems rather than a general ledger or bank record.';

create table if not exists energy.valuation_snapshots (
  valuation_id uuid primary key default gen_random_uuid(),
  financial_model_id uuid not null references energy.financial_models(financial_model_id) on delete cascade,
  valuation_date date not null,
  valuation_method text not null check (valuation_method in ('DCF','NPV','COMPARABLES_REFERENCE','TRANSACTION_REFERENCE','REPLACEMENT_COST_REFERENCE','NAV_REFERENCE','OTHER')),
  enterprise_value numeric,
  equity_value numeric,
  npv numeric,
  irr_pct numeric check (irr_pct is null or irr_pct > -1000),
  payback_years numeric check (payback_years is null or payback_years >= 0),
  discount_rate_pct numeric check (discount_rate_pct is null or discount_rate_pct >= 0),
  currency_code text not null default 'USD' check (currency_code ~ '^[A-Z]{3}$'),
  valuation_state text not null default 'MODEL_OUTPUT' check (valuation_state in ('MODEL_OUTPUT','IN_REVIEW','REFERENCE_VERIFIED','APPROVED_REFERENCE','SUPERSEDED','DISPUTED','ARCHIVED')),
  verification_state text not null default 'UNVERIFIED' check (verification_state in ('UNVERIFIED','PENDING_VERIFICATION','REFERENCE_VERIFIED','VERIFIED','DISPUTED','ARCHIVED')),
  evidence_reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
comment on table energy.valuation_snapshots is 'Valuation outputs for internal/reference use. No row constitutes an appraisal, fairness opinion, securities valuation, lender commitment, or guaranteed realization value.';

create table if not exists energy.capital_readiness_assessments (
  assessment_id uuid primary key default gen_random_uuid(),
  project_id uuid not null references energy.projects(project_id) on delete cascade,
  assessment_date date not null default current_date,
  readiness_state text not null default 'NOT_ASSESSED' check (readiness_state in ('NOT_ASSESSED','EARLY','DEVELOPING','DILIGENCE_READY','INVESTMENT_COMMITTEE_READY_REFERENCE','FINANCING_READY_REFERENCE','CONDITIONAL','BLOCKED','ARCHIVED')),
  technical_score numeric check (technical_score is null or (technical_score between 0 and 100)),
  commercial_score numeric check (commercial_score is null or (commercial_score between 0 and 100)),
  regulatory_score numeric check (regulatory_score is null or (regulatory_score between 0 and 100)),
  operational_score numeric check (operational_score is null or (operational_score between 0 and 100)),
  financial_score numeric check (financial_score is null or (financial_score between 0 and 100)),
  evidence_score numeric check (evidence_score is null or (evidence_score between 0 and 100)),
  overall_score numeric check (overall_score is null or (overall_score between 0 and 100)),
  blocking_conditions text,
  evidence_reference text,
  verification_state text not null default 'UNVERIFIED' check (verification_state in ('UNVERIFIED','PENDING_VERIFICATION','REFERENCE_VERIFIED','VERIFIED','DISPUTED','ARCHIVED')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
comment on table energy.capital_readiness_assessments is 'Internal readiness assessment only. FINANCING_READY_REFERENCE does not mean financing is committed, funded, approved by a lender, or available for draw.';

create table if not exists energy.capital_requirements (
  requirement_id uuid primary key default gen_random_uuid(),
  project_id uuid not null references energy.projects(project_id) on delete cascade,
  requirement_type text not null check (requirement_type in ('DEVELOPMENT_CAPITAL','CONSTRUCTION_DEBT','CONSTRUCTION_EQUITY','TERM_DEBT','TAX_EQUITY_REFERENCE','WORKING_CAPITAL','GUARANTEE_REFERENCE','CREDIT_SUPPORT_REFERENCE','GRANT_REFERENCE','OTHER')),
  requested_amount numeric check (requested_amount is null or requested_amount >= 0),
  currency_code text not null default 'USD' check (currency_code ~ '^[A-Z]{3}$'),
  requirement_state text not null default 'INDICATIVE' check (requirement_state in ('INDICATIVE','QUALIFYING','DILIGENCE','REFERRED','TERM_SHEET_REFERENCE','COMMITMENT_REFERENCE','FUNDED_REFERENCE','WITHDRAWN','REJECTED','ARCHIVED')),
  evidence_reference text,
  target_close_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (requirement_state not in ('TERM_SHEET_REFERENCE','COMMITMENT_REFERENCE','FUNDED_REFERENCE') or evidence_reference is not null)
);
comment on table energy.capital_requirements is 'Capital need and financing-reference registry. Commitment, term-sheet, or funded states require evidence and remain references to authoritative finance records.';

create table if not exists energy.finance_external_references (
  finance_reference_id uuid primary key default gen_random_uuid(),
  project_id uuid not null references energy.projects(project_id) on delete cascade,
  financial_model_id uuid references energy.financial_models(financial_model_id) on delete set null,
  system_name text not null check (system_name in ('HEI','RW','WIM','IOTF','SETC','BANK_REFERENCE','LENDER_REFERENCE','INVESTOR_REFERENCE','OTHER')),
  external_entity_type text not null check (external_entity_type in ('CAPITAL_PROJECT','INVESTMENT_OPPORTUNITY','INVESTMENT_INDICATION','INVESTMENT_DECISION','INVESTMENT_COMMITMENT','FUNDING_SOURCE','FUNDING_AWARD','FUNDING_ALLOCATION','FUNDING_RECEIPT','CAPITAL_REQUEST','CAPITAL_REFERRAL','INVESTMENT_PROJECT','TRANSACTION','SETTLEMENT_EVENT','OTHER')),
  external_reference text not null,
  relationship_type text not null default 'REFERENCE_ONLY' check (relationship_type in ('REFERENCE_ONLY','ECONOMIC_SUPPORT','FINANCING_PIPELINE','COMMITMENT_REFERENCE','FUNDING_REFERENCE','SETTLEMENT_REFERENCE','OTHER')),
  state text not null default 'REFERENCE' check (state in ('REFERENCE','PENDING_VERIFICATION','VERIFIED_REFERENCE','RECONCILED','DISPUTED','ARCHIVED')),
  evidence_reference text,
  observed_at timestamptz not null default now(),
  unique(system_name, external_entity_type, external_reference)
);
comment on table energy.finance_external_references is 'Reference-only bridge to authoritative HEI/RW/WIM/IOTF or third-party finance records. This table does not originate funding, commitments, receipts, settlement, or bank balances.';

alter table energy.financial_models enable row level security;
alter table energy.financial_assumptions enable row level security;
alter table energy.cash_flow_projections enable row level security;
alter table energy.valuation_snapshots enable row level security;
alter table energy.capital_readiness_assessments enable row level security;
alter table energy.capital_requirements enable row level security;
alter table energy.finance_external_references enable row level security;

revoke all on energy.financial_models, energy.financial_assumptions, energy.cash_flow_projections, energy.valuation_snapshots, energy.capital_readiness_assessments, energy.capital_requirements, energy.finance_external_references from anon, authenticated;
grant all on energy.financial_models, energy.financial_assumptions, energy.cash_flow_projections, energy.valuation_snapshots, energy.capital_readiness_assessments, energy.capital_requirements, energy.finance_external_references to service_role;

create index if not exists idx_energy_fin_models_project on energy.financial_models(project_id) where project_id is not null;
create index if not exists idx_energy_fin_models_asset on energy.financial_models(asset_id) where asset_id is not null;
create index if not exists idx_energy_fin_assumptions_model on energy.financial_assumptions(financial_model_id);
create index if not exists idx_energy_cashflows_model_period on energy.cash_flow_projections(financial_model_id, period_start);
create index if not exists idx_energy_valuation_model_date on energy.valuation_snapshots(financial_model_id, valuation_date desc);
create index if not exists idx_energy_cap_readiness_project_date on energy.capital_readiness_assessments(project_id, assessment_date desc);
create index if not exists idx_energy_cap_requirements_project on energy.capital_requirements(project_id);
create index if not exists idx_energy_fin_external_project on energy.finance_external_references(project_id);
create index if not exists idx_energy_fin_external_model on energy.finance_external_references(financial_model_id) where financial_model_id is not null;
