create table if not exists public.set_sourcecube_labs (
  id bigint generated by default as identity primary key,
  lab_code text not null unique,
  lab_name text not null,
  cohort_code text not null unique,
  governing_entity text not null default 'SourceEnergy Technologies',
  lab_role text not null default 'governed innovation workspace',
  ip_owner_role text not null default 'not an IP owner',
  onboarding_state text not null default 'assigned',
  evidence_drive_folder_id text,
  registry_drive_folder_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.set_sourcecube_lab_technology_links (
  id bigint generated by default as identity primary key,
  sourcecube_lab_id bigint not null references public.set_sourcecube_labs(id) on delete restrict,
  technology_registry_id bigint not null references public.seg_technology_registry(id) on delete restrict,
  relationship_type text not null default 'cohort technology workspace',
  created_at timestamptz not null default now(),
  unique(sourcecube_lab_id, technology_registry_id)
);

comment on table public.set_sourcecube_labs is 'One SourceCube Lab is assigned to each SourceEnergy Technologies cohort at onboarding. The Lab is an operational/governance workspace and does not itself own IP.';
comment on column public.set_sourcecube_labs.governing_entity is 'SourceEnergy Technologies governs Cohort IP; source/provenance licensors such as NASA are not substituted as Cohort IP owner.';
