create table if not exists public.set_genesis_cubes (
 id bigint generated by default as identity primary key,
 genesis_cube_code text not null unique,
 person_key text not null unique,
 display_name text not null,
 genesis_block text not null default 'G-Block / L1 Genesis',
 lifecycle_state text not null default 'onboarded',
 ip_owner_role text not null default 'not an IP ownership record',
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create table if not exists public.set_genesis_cube_lab_memberships (
 id bigint generated by default as identity primary key,
 genesis_cube_id bigint not null references public.set_genesis_cubes(id) on delete restrict,
 sourcecube_lab_id bigint not null references public.set_sourcecube_labs(id) on delete restrict,
 cohort_role text not null default 'participant',
 membership_state text not null default 'historical-onboarding',
 joined_at timestamptz,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),
 unique(genesis_cube_id,sourcecube_lab_id)
);
create table if not exists public.set_genesis_cube_contributions (
 id bigint generated by default as identity primary key,
 genesis_cube_id bigint not null references public.set_genesis_cubes(id) on delete restrict,
 technology_registry_id bigint references public.seg_technology_registry(id) on delete restrict,
 contribution_type text not null,
 evidence_reference text,
 inventorship_status text not null default 'not determined',
 ownership_status text not null default 'not determined',
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
comment on table public.set_genesis_cubes is 'Persistent person-level Genesis Cube assigned at G-Block onboarding. One person retains one Genesis Cube across cohorts and ventures.';
comment on table public.set_genesis_cube_contributions is 'Contribution provenance only. A contribution link does not establish inventorship, ownership, assignment, or licensing rights.';
