create table if not exists iotf.instrument_authority_matrix (
 id uuid primary key default gen_random_uuid(), instrument_id uuid not null references iotf.instruments(id) on delete cascade, wim_organization_id uuid not null references wim.organizations(id) on delete restrict, authority_code text not null, authority_class text not null check (authority_class in ('ORIGINATION','ADVISORY','STRUCTURING','GOVERNANCE','EVIDENCE','LOGISTICS','SECTOR_DEMAND','SETTLEMENT')), authority_mode text not null check (authority_mode in ('PERMITTED','RECOMMEND_ONLY','CONTROL_ONLY','EXECUTION_SUPPORT')), may_originate boolean not null default false, may_recommend boolean not null default false, may_structure boolean not null default false, may_govern boolean not null default false, may_submit_evidence boolean not null default false, may_execute_logistics boolean not null default false, may_settle boolean not null default false, may_unilaterally_authorize_instrument_use boolean not null default false, transaction_specific_g4_required boolean not null default true, status text not null default 'ACTIVE' check(status in ('ACTIVE','SUSPENDED','INACTIVE')), mandate text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(instrument_id,wim_organization_id,authority_code));
alter table iotf.instrument_authority_matrix enable row level security; revoke all on iotf.instrument_authority_matrix from public,anon,authenticated; grant select,insert,update,delete on iotf.instrument_authority_matrix to service_role; create index if not exists iotf_instrument_authority_matrix_idx on iotf.instrument_authority_matrix(instrument_id,wim_organization_id,status);
insert into iotf.instrument_authority_matrix(instrument_id,wim_organization_id,authority_code,authority_class,authority_mode,may_originate,may_recommend,may_structure,may_govern,may_submit_evidence,may_execute_logistics,may_settle,may_unilaterally_authorize_instrument_use,transaction_specific_g4_required,mandate,metadata)
select i.id,o.id,x.code,x.class,x.mode,x.orig,x.rec,x.struct,x.gov,x.evid,x.logi,x.settle,false,true,x.mandate,jsonb_build_object('segregation_of_duties',true,'instrument_use_authority','TRANSACTION_SPECIFIC_ONLY')
from iotf.instruments i cross join (values
 ('SourceEnergy Foundation','BENEFICIARY_PRINCIPAL','GOVERNANCE','CONTROL_ONLY',false,false,false,true,true,false,false,'Strategic principal and stated beneficiary; may govern and provide beneficiary evidence but may not unilaterally authorize utilization.'),
 ('SourceEnergy Global','PRIMARY_TRADE_ORIGINATOR','ORIGINATION','PERMITTED',true,false,false,false,true,false,false,'Primary procurement and trade originator for eligible physical-goods transactions.'),
 ('Energy Source Business','OMAN_ENERGY_ORIGINATOR','ORIGINATION','PERMITTED',true,false,false,false,true,false,false,'Oman/GCC energy buyer, seller and transaction originator; underlying commercial party, not SBLC holder or beneficiary.'),
 ('SourceEnergy Capital','CAPITAL_STRUCTURER','STRUCTURING','PERMITTED',false,false,true,false,true,false,false,'Structures transaction capitalization, facility economics and capacity requirements without banking authentication authority.'),
 ('SourceEnergy ScrollBank and Covenant Trust','TREASURY_EVIDENCE_GOVERNOR','GOVERNANCE','CONTROL_ONLY',false,false,false,true,true,false,true,'Controls instrument registry, treasury governance, evidence custody and settlement governance; no unilateral G4 authority.'),
 ('SourceEnergy Wealth Advisors','WEALTH_RISK_ADVISOR','ADVISORY','RECOMMEND_ONLY',false,true,false,false,false,false,false,'Provides risk, portfolio and Wealth Ecology recommendations; non-custodial and non-executing.'),
 ('Robert Global Logistics LLC','LOGISTICS_EXECUTION','LOGISTICS','EXECUTION_SUPPORT',false,false,false,false,true,true,false,'Executes logistics and supplies shipment/delivery evidence for approved transactions.'),
 ('Diaspora Health Group','SECTOR_BUYER','SECTOR_DEMAND','PERMITTED',true,false,false,false,true,false,false,'Healthcare-sector buyer and demand originator for qualifying physical-goods procurement.')
) x(name,code,class,mode,orig,rec,struct,gov,evid,logi,settle,mandate) join wim.organizations o on lower(o.legal_name)=lower(x.name)
where i.external_reference='SBLC-20260820-0001-14'
on conflict(instrument_id,wim_organization_id,authority_code) do update set authority_mode=excluded.authority_mode,may_originate=excluded.may_originate,may_recommend=excluded.may_recommend,may_structure=excluded.may_structure,may_govern=excluded.may_govern,may_submit_evidence=excluded.may_submit_evidence,may_execute_logistics=excluded.may_execute_logistics,may_settle=excluded.may_settle,may_unilaterally_authorize_instrument_use=false,transaction_specific_g4_required=true,mandate=excluded.mandate,metadata=iotf.instrument_authority_matrix.metadata||excluded.metadata,updated_at=now();
create or replace function iotf.enforce_transaction_authority_separation() returns trigger language plpgsql security invoker set search_path=iotf,pg_temp as $$ begin if new.may_unilaterally_authorize_instrument_use then raise exception 'No organization may receive unilateral instrument-use authority; transaction-specific G4 control is mandatory'; end if; if new.may_originate and new.may_govern then raise exception 'Segregation of duties violation: same authority record cannot both originate and govern'; end if; if new.may_recommend and (new.may_settle or new.may_govern) then raise exception 'Segregation of duties violation: advisory authority cannot also govern or settle'; end if; return new; end; $$;
drop trigger if exists trg_iotf_authority_separation on iotf.instrument_authority_matrix; create trigger trg_iotf_authority_separation before insert or update on iotf.instrument_authority_matrix for each row execute function iotf.enforce_transaction_authority_separation();
create or replace view iotf.sblc_authority_control_matrix with(security_invoker=true) as select i.instrument_code,o.legal_name,a.authority_code,a.authority_class,a.authority_mode,a.may_originate,a.may_recommend,a.may_structure,a.may_govern,a.may_submit_evidence,a.may_execute_logistics,a.may_settle,a.may_unilaterally_authorize_instrument_use,a.transaction_specific_g4_required,a.status,a.mandate from iotf.instrument_authority_matrix a join iotf.instruments i on i.id=a.instrument_id join wim.organizations o on o.id=a.wim_organization_id; revoke all on iotf.sblc_authority_control_matrix from public,anon,authenticated; grant select on iotf.sblc_authority_control_matrix to service_role;
