insert into wim.economic_subclusters (cluster_id, source_subcluster_number, canonical_code, name, source_url, status)
select c.id, v.sub_no, c.canonical_code || '-S' || lpad(v.sub_no::text,2,'0'), v.name, 'https://wimexchange.com/the-west-indies-trading-company/', 'active'
from (values
(101,1,'Food and Beverage Stores'),(101,2,'Food Services and Drinking Places'),(101,3,'Food Manufacturing'),(101,4,'Beverage Manufacturing'),(101,5,'Food Wholesalers'),(101,6,'Beverage Wholesalers'),(101,7,'Specialty Food Stores'),
(102,1,'Personal Care Services'),(102,2,'Death Care Services'),(102,3,'Laundry and Drycleaning Services'),(102,4,'Pet Care Services'),(102,5,'Photographic Services'),(102,6,'Other Personal Services'),(102,7,'Repair and Maintenance'),
(103,1,'Hospitals'),(103,2,'Physicians'),(103,3,'Dentists'),(103,4,'Other Health Practitioners'),(103,5,'Outpatient Care Centers'),(103,6,'Medical and Diagnostic Laboratories'),(103,7,'Home Health Care Services'),(103,8,'Nursing and Residential Care Facilities'),
(104,1,'Water Supply and Irrigation Systems'),(104,2,'Sewage Treatment Facilities'),(104,3,'Natural Gas Distribution'),(104,4,'Electric Power Distribution'),(104,5,'Waste Management and Remediation Services'),
(105,1,'Taxi and Limousine Service'),(105,2,'School and Employee Bus Transportation'),(105,3,'Charter Bus Industry'),(105,4,'Scenic and Sightseeing Transportation'),(105,5,'Other Transit and Ground Passenger Transportation'),
(106,1,'Furniture Stores'),(106,2,'Home Furnishings Stores'),(106,3,'Electronics and Appliance Stores'),(106,4,'Building Material and Supplies Dealers'),(106,5,'Lawn and Garden Equipment and Supplies Stores'),(106,6,'Household Appliance Repair'),(106,7,'Other Household Goods Repair and Maintenance'),
(107,1,'Depository Credit Intermediation'),(107,2,'Nondepository Credit Intermediation'),(107,3,'Activities Related to Credit Intermediation'),(107,4,'Insurance Agencies and Brokerages'),(107,5,'Other Financial Investment Activities'),
(108,1,'Automobile Dealers'),(108,2,'Other Motor Vehicle Dealers'),(108,3,'Automotive Parts, Accessories, and Tire Stores'),(108,4,'Automotive Repair and Maintenance'),(108,5,'Automotive Equipment Rental and Leasing'),(108,6,'Motor Vehicle Towing'),(108,7,'Parking Lots and Garages'),(108,8,'Car Washes'),(108,9,'Gasoline Stations'),
(109,1,'Clothing Stores'),(109,2,'Shoe Stores'),(109,3,'Jewelry, Luggage, and Leather Goods Stores'),(109,4,'Department Stores'),(109,5,'Other General Merchandise Stores'),
(110,1,'Motion Picture and Video Exhibition'),(110,2,'Radio and Television Broadcasting'),(110,3,'Cable and Other Subscription Programming'),(110,4,'Other Information Services'),(110,5,'Promoters of Performing Arts, Sports, and Similar Events'),(110,6,'Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures'),(110,7,'Independent Artists, Writers, and Performers'),(110,8,'Amusement Parks and Arcades'),
(111,1,'Hotels and Motels'),(111,2,'Other Traveler Accommodation'),(111,3,'RV Parks and Recreational Camps'),
(112,1,'Legal Services'),(112,2,'Accounting, Tax Preparation, Bookkeeping, and Payroll Services'),(112,3,'Architectural, Engineering, and Related Services'),(112,4,'Specialized Design Services'),(112,5,'Management, Scientific, and Technical Consulting Services'),(112,6,'Advertising, Public Relations, and Related Services'),(112,7,'Other Professional, Scientific, and Technical Services'),(112,8,'Office Administrative Services'),
(113,1,'Elementary and Secondary Schools'),(113,2,'Junior Colleges'),(113,3,'Colleges, Universities, and Professional Schools'),
(114,1,'Religious Organizations'),(114,2,'Grantmaking and Giving Services'),(114,3,'Social Advocacy Organizations'),(114,4,'Civic and Social Organizations'),(114,5,'Business, Professional, Labor, Political, and Similar Organizations'),(114,6,'Other Similar Organizations'),
(115,1,'Lessors of Real Estate'),(115,2,'Offices of Real Estate Agents and Brokers'),(115,3,'Activities Related to Real Estate'),(115,4,'Residential Building Construction'),(115,5,'Nonresidential Building Construction'),(115,6,'Utility System Construction'),(115,7,'Land Subdivision'),(115,8,'Highway, Street, and Bridge Construction'),(115,9,'Other Heavy and Civil Engineering Construction'),(115,10,'Specialty Trade Contractors'),
(116,1,'Commercial and Industrial Machinery and Equipment Repair and Maintenance'),(116,2,'Electronic and Precision Equipment Repair and Maintenance'),(116,3,'Personal and Household Goods Repair and Maintenance'),(116,4,'Other Repair and Maintenance')
) as v(cluster_no,sub_no,name)
join wim.economic_clusters c on c.source_cluster_number=v.cluster_no and c.cluster_scope='local'
on conflict (canonical_code) do nothing;
