create table if not exists public.seg_markets (
  id bigint generated by default as identity primary key,
  market_code text not null unique,
  name text not null,
  region text,
  jurisdiction_code text,
  market_type text not null default 'geographic',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seg_project_markets (
  project_id bigint not null references public.hei_capital_projects(id) on delete cascade,
  market_id bigint not null references public.seg_markets(id) on delete cascade,
  relationship_type text not null default 'delivery_market',
  created_at timestamptz not null default now(),
  primary key (project_id, market_id, relationship_type)
);

create table if not exists public.seg_evidence_items (
  id bigint generated by default as identity primary key,
  evidence_reference text not null unique,
  title text not null,
  evidence_type text not null,
  source_uri text,
  source_organization_oid text references public.setc_organizations(oid),
  evidence_level smallint not null default 0 check (evidence_level between 0 and 5),
  verification_state text not null default 'unverified',
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seg_contracts (
  id bigint generated by default as identity primary key,
  contract_reference text not null unique,
  project_id bigint references public.hei_capital_projects(id),
  principal_organization_oid text references public.setc_organizations(oid),
  counterparty_organization_oid text references public.setc_organizations(oid),
  contract_type text not null,
  status text not null default 'draft',
  effective_date date,
  expiration_date date,
  evidence_level smallint not null default 0 check (evidence_level between 0 and 5),
  evidence_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seg_claims (
  id bigint generated by default as identity primary key,
  claim_reference text not null unique,
  claim_class text not null check (claim_class in ('C1','C2','C3','C4','C5','C6','C7','C8','C9','C10')),
  subject_type text not null,
  organization_oid text references public.setc_organizations(oid),
  project_id bigint references public.hei_capital_projects(id),
  ip_asset_id bigint references public.hei_ip_assets(id),
  statement text not null,
  publication_state text not null default 'internal',
  evidence_level smallint not null default 0 check (evidence_level between 0 and 5),
  last_verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (organization_oid is not null or project_id is not null or ip_asset_id is not null)
);

create table if not exists public.seg_claim_evidence (
  claim_id bigint not null references public.seg_claims(id) on delete cascade,
  evidence_id bigint not null references public.seg_evidence_items(id) on delete cascade,
  support_type text not null default 'supports',
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (claim_id, evidence_id)
);

create table if not exists public.seg_technology_registry (
  id bigint generated by default as identity primary key,
  technology_reference text not null unique,
  ip_asset_id bigint references public.hei_ip_assets(id),
  owning_organization_oid text references public.setc_organizations(oid),
  name text not null,
  maturity_state text not null default 'concept',
  commercialization_state text not null default 'research',
  evidence_level smallint not null default 0 check (evidence_level between 0 and 5),
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seg_products_services (
  id bigint generated by default as identity primary key,
  product_reference text not null unique,
  technology_id bigint references public.seg_technology_registry(id),
  provider_organization_oid text references public.setc_organizations(oid),
  name text not null,
  product_type text not null,
  market_readiness text not null default 'development',
  evidence_level smallint not null default 0 check (evidence_level between 0 and 5),
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists seg_claims_org_idx on public.seg_claims(organization_oid);
create index if not exists seg_claims_project_idx on public.seg_claims(project_id);
create index if not exists seg_contracts_project_idx on public.seg_contracts(project_id);
create index if not exists seg_contracts_principal_idx on public.seg_contracts(principal_organization_oid);
create index if not exists seg_contracts_counterparty_idx on public.seg_contracts(counterparty_organization_oid);
create index if not exists seg_evidence_source_org_idx on public.seg_evidence_items(source_organization_oid);
create index if not exists seg_project_markets_market_idx on public.seg_project_markets(market_id);
create index if not exists seg_technology_owner_idx on public.seg_technology_registry(owning_organization_oid);
create index if not exists seg_products_provider_idx on public.seg_products_services(provider_organization_oid);

alter table public.seg_markets enable row level security;
alter table public.seg_project_markets enable row level security;
alter table public.seg_evidence_items enable row level security;
alter table public.seg_contracts enable row level security;
alter table public.seg_claims enable row level security;
alter table public.seg_claim_evidence enable row level security;
alter table public.seg_technology_registry enable row level security;
alter table public.seg_products_services enable row level security;

revoke all on table public.seg_markets from anon, authenticated;
revoke all on table public.seg_project_markets from anon, authenticated;
revoke all on table public.seg_evidence_items from anon, authenticated;
revoke all on table public.seg_contracts from anon, authenticated;
revoke all on table public.seg_claims from anon, authenticated;
revoke all on table public.seg_claim_evidence from anon, authenticated;
revoke all on table public.seg_technology_registry from anon, authenticated;
revoke all on table public.seg_products_services from anon, authenticated;

create policy seg_markets_service_role_all on public.seg_markets for all to service_role using (true) with check (true);
create policy seg_project_markets_service_role_all on public.seg_project_markets for all to service_role using (true) with check (true);
create policy seg_evidence_items_service_role_all on public.seg_evidence_items for all to service_role using (true) with check (true);
create policy seg_contracts_service_role_all on public.seg_contracts for all to service_role using (true) with check (true);
create policy seg_claims_service_role_all on public.seg_claims for all to service_role using (true) with check (true);
create policy seg_claim_evidence_service_role_all on public.seg_claim_evidence for all to service_role using (true) with check (true);
create policy seg_technology_registry_service_role_all on public.seg_technology_registry for all to service_role using (true) with check (true);
create policy seg_products_services_service_role_all on public.seg_products_services for all to service_role using (true) with check (true);
