delete from wim.economic_clusters;

insert into wim.economic_clusters (canonical_code, source_cluster_number, name, cluster_scope, source_url, verification_status) values
('WIM-T01',1,'Aerospace Vehicles and Defense','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T02',2,'Agricultural Inputs and Services','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T03',3,'Apparel','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T04',4,'Automotive','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T05',5,'Biopharmaceuticals','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T06',6,'Business Services','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T07',7,'Coal Mining','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T08',8,'Communications Equipment and Services','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T09',9,'Construction Products and Services','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T10',10,'Distribution and Electronic Commerce','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T11',11,'Downstream Chemical Products','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T12',12,'Downstream Metal Products','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T13',13,'Education and Knowledge Creation','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T14',14,'Electric Power Generation and Transmission','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T15',15,'Environmental Services','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T16',16,'Financial Services','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T17',17,'Fishing and Fishing Products','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T18',18,'Food Processing and Manufacturing','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T19',19,'Footwear','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T20',20,'Forestry','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T21',21,'Furniture','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T22',22,'Hospitality and Tourism','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T23',23,'Information Technology and Analytical Instruments','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T24',24,'Insurance Services','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T25',25,'Jewelry and Precious Metals','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T26',26,'Leather and Related Products','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T27',27,'Lighting and Electrical Equipment','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T28',28,'Livestock Processing','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T29',29,'Marketing, Design, and Publishing','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T30',30,'Medical Devices','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T31',31,'Metal Mining','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T32',32,'Metalworking Technology','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T33',33,'Music and Sound Recording','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T34',34,'Nonmetal Mining','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T35',35,'Oil and Gas Production and Transportation','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T36',36,'Paper and Packaging','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T37',37,'Performing Arts','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T38',38,'Plastics','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T39',39,'Printing Services','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T40',40,'Production Technology and Heavy Machinery','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T41',41,'Recreational and Small Electric Goods','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T42',42,'Textile Manufacturing','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T43',43,'Tobacco','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T44',44,'Trailers, Motor Homes, and Appliances','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T45',45,'Transportation and Logistics','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T46',46,'Upstream Chemical Products','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T47',47,'Upstream Metal Manufacturing','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T48',48,'Video Production and Distribution','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T49',49,'Vulcanized and Fired Materials','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T50',50,'Water Transportation','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-T51',51,'Wood Products','traded','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L01',101,'Local Food and Beverage Processing and Distribution','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L02',102,'Local Personal Services (Non-Medical)','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L03',103,'Local Health Services','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L04',104,'Local Utilities','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L05',105,'Local Logistical Services','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L06',106,'Local Household Goods and Services','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L07',107,'Local Financial Services','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L08',108,'Local Motor Vehicle Products and Services','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L09',109,'Local Retailing of Clothing and General Merchandise','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L10',110,'Local Entertainment and Media','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L11',111,'Local Hospitality Establishments','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L12',112,'Local Commercial Services','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L13',113,'Local Education and Training','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L14',114,'Local Community and Civic Organizations','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L15',115,'Local Real Estate, Construction, and Development','local','https://wimexchange.com/the-west-indies-trading-company/','verified'),
('WIM-L16',116,'Local Industrial Products and Services','local','https://wimexchange.com/the-west-indies-trading-company/','verified');
