update wim.economic_clusters set name='Biopharmaceuticals', source_url='https://wimexchange.com/the-west-indies-trading-company/' where canonical_code='WIM-T11';
update wim.economic_clusters set name='Production Technology and Heavy Machinery' where canonical_code='WIM-T12';
update wim.economic_clusters set name='Upstream Metal Manufacturing' where canonical_code='WIM-T13';
update wim.economic_clusters set name='Downstream Metal Products' where canonical_code='WIM-T14';
update wim.economic_clusters set name='Oil and Gas Production and Transportation' where canonical_code='WIM-T15';
update wim.economic_clusters set name='Furniture' where canonical_code='WIM-T16';
update wim.economic_clusters set name='Business Services' where canonical_code='WIM-T17';
update wim.economic_clusters set name='Marketing, Design and Publishing' where canonical_code='WIM-T18';
update wim.economic_clusters set name='Performing Arts' where canonical_code='WIM-T19';
update wim.economic_clusters set name='Vulcanized and Fired Materials' where canonical_code='WIM-T20';
update wim.economic_clusters set name='Information Technology and Analytical Instruments' where canonical_code='WIM-T21';
update wim.economic_clusters set name='Textile Manufacturing' where canonical_code='WIM-T22';
update wim.economic_clusters set name='Apparel' where canonical_code='WIM-T23';
update wim.economic_clusters set name='Lighting and Electrical Equipment' where canonical_code='WIM-T24';
update wim.economic_clusters set name='Communications Equipment and Services' where canonical_code='WIM-T25';
update wim.economic_clusters set name='Distribution and Electronic Commerce' where canonical_code='WIM-T26';
update wim.economic_clusters set name='Plastics' where canonical_code='WIM-T27';
update wim.economic_clusters set name='Leather and Related Products' where canonical_code='WIM-T28';
update wim.economic_clusters set name='Insurance Services' where canonical_code='WIM-T29';
update wim.economic_clusters set name='Printing Services' where canonical_code='WIM-T30';
update wim.economic_clusters set name='Environmental Services' where canonical_code='WIM-T31';
update wim.economic_clusters set name='Video Production and Distribution' where canonical_code='WIM-T32';
update wim.economic_clusters set name='Music and Sound Recording' where canonical_code='WIM-T33';
update wim.economic_clusters set name='Recreational and Small Electric Goods' where canonical_code='WIM-T34';
update wim.economic_clusters set name='Automotive' where canonical_code='WIM-T35';
update wim.economic_clusters set name='Aerospace and Defense' where canonical_code='WIM-T36';
update wim.economic_clusters set name='Trailers, Motor Homes and Appliances' where canonical_code='WIM-T37';
update wim.economic_clusters set name='Metal Mining' where canonical_code='WIM-T38';
update wim.economic_clusters set name='Tobacco' where canonical_code='WIM-T39';
update wim.economic_clusters set name='Footwear' where canonical_code='WIM-T40';
update wim.economic_clusters set name='Livestock Processing' where canonical_code='WIM-T41';
update wim.economic_clusters set name='Water Transportation' where canonical_code='WIM-T42';
update wim.economic_clusters set name='Fishing and Fishing Products' where canonical_code='WIM-T43';
update wim.economic_clusters set name='Coal Mining' where canonical_code='WIM-T44';
update wim.economic_clusters set name='Oil and Gas Products and Services' where canonical_code='WIM-T45';
update wim.economic_clusters set name='Paper and Packaging' where canonical_code='WIM-T46';
update wim.economic_clusters set name='Transportation and Logistics' where canonical_code='WIM-T47';
update wim.economic_clusters set name='Hospitality and Tourism' where canonical_code='WIM-T48';
update wim.economic_clusters set name='Jewelry and Precious Metals' where canonical_code='WIM-T49';
update wim.economic_clusters set name='Medical Devices' where canonical_code='WIM-T50';
