alter function wim.enforce_organization_commercial_status() set search_path = pg_catalog,wim;
alter function wim.enforce_product_service_publishability() set search_path = pg_catalog,wim;
alter function wim.restrict_offerings_for_organization() set search_path = pg_catalog,wim;
alter function wim.enforce_opportunity_state() set search_path = pg_catalog,wim;
alter function wim.enforce_opportunity_response() set search_path = pg_catalog,wim;
alter function wim.restrict_opportunities_for_organization() set search_path = pg_catalog,wim;
alter function wim.enforce_trade_progression() set search_path = pg_catalog,wim;
alter function wim.audit_trade_state_change() set search_path = pg_catalog,wim;
alter function wim.enforce_settlement_request() set search_path = pg_catalog,wim;
alter function wim.audit_settlement_request() set search_path = pg_catalog,wim;
alter function wim.enforce_impact_metric() set search_path = pg_catalog,wim;
alter function wim.audit_impact_correction() set search_path = pg_catalog,wim;

revoke execute on function wim.enforce_organization_commercial_status() from public, anon, authenticated;
revoke execute on function wim.enforce_product_service_publishability() from public, anon, authenticated;
revoke execute on function wim.restrict_offerings_for_organization() from public, anon, authenticated;
revoke execute on function wim.enforce_opportunity_state() from public, anon, authenticated;
revoke execute on function wim.enforce_opportunity_response() from public, anon, authenticated;
revoke execute on function wim.restrict_opportunities_for_organization() from public, anon, authenticated;
revoke execute on function wim.enforce_trade_progression() from public, anon, authenticated;
revoke execute on function wim.audit_trade_state_change() from public, anon, authenticated;
revoke execute on function wim.enforce_settlement_request() from public, anon, authenticated;
revoke execute on function wim.audit_settlement_request() from public, anon, authenticated;
revoke execute on function wim.enforce_impact_metric() from public, anon, authenticated;
revoke execute on function wim.audit_impact_correction() from public, anon, authenticated;

grant execute on function wim.enforce_organization_commercial_status() to service_role;
grant execute on function wim.enforce_product_service_publishability() to service_role;
grant execute on function wim.restrict_offerings_for_organization() to service_role;
grant execute on function wim.enforce_opportunity_state() to service_role;
grant execute on function wim.enforce_opportunity_response() to service_role;
grant execute on function wim.restrict_opportunities_for_organization() to service_role;
grant execute on function wim.enforce_trade_progression() to service_role;
grant execute on function wim.audit_trade_state_change() to service_role;
grant execute on function wim.enforce_settlement_request() to service_role;
grant execute on function wim.audit_settlement_request() to service_role;
grant execute on function wim.enforce_impact_metric() to service_role;
grant execute on function wim.audit_impact_correction() to service_role;

create index if not exists idx_wim_commercialization_lead_org on wim.commercialization_projects(lead_organization_id);
create index if not exists idx_wim_commercialization_research_asset on wim.commercialization_projects(research_asset_id);
create index if not exists idx_wim_commercialization_opportunity on wim.commercialization_projects(opportunity_id);
create index if not exists idx_wim_impact_correction_metric on wim.impact_metric_corrections(impact_metric_id);
create index if not exists idx_wim_impact_corrected_from on wim.impact_metrics(corrected_from_impact_metric_id);
create index if not exists idx_wim_opportunities_matched_org on wim.opportunities(matched_organization_id);
create index if not exists idx_wim_opportunities_subcluster on wim.opportunities(subcluster_id);
create index if not exists idx_wim_opportunity_responses_org on wim.opportunity_responses(responding_organization_id);
create index if not exists idx_wim_org_cluster_subcluster on wim.organization_cluster_memberships(subcluster_id);
create index if not exists idx_wim_research_cluster on wim.research_assets(cluster_id);
create index if not exists idx_wim_research_subcluster on wim.research_assets(subcluster_id);
create index if not exists idx_wim_settlement_correction_request on wim.settlement_corrections(settlement_request_id);
create index if not exists idx_wim_source_coin_events_txn on wim.source_coin_events(transaction_id);
create index if not exists idx_wim_trade_corrections_txn on wim.trade_corrections(transaction_id);
create index if not exists idx_wim_trade_corridor_destination on wim.trade_corridors(destination_market_id);
create index if not exists idx_wim_transactions_buyer on wim.transactions(buyer_organization_id);
create index if not exists idx_wim_transactions_seller on wim.transactions(seller_organization_id);
create index if not exists idx_wim_transactions_opportunity on wim.transactions(opportunity_id);
