alter table sourceenergy_one.spirit_gate_assessments add column if not exists supersedes_assessment_id uuid references sourceenergy_one.spirit_gate_assessments(id);
alter table sourceenergy_one.spirit_gate_assessments drop constraint if exists spirit_gate_assessments_object_type_object_ref_gate_version_key;
create unique index if not exists spirit_gate_one_confirmed_per_object_version_idx on sourceenergy_one.spirit_gate_assessments(object_type,object_ref,gate_version) where status='human_confirmed';

create or replace function sourceenergy_one.assess_spirit_gate_v3(p_subject_id text,p_object_type text,p_object_ref uuid,p_dimension_findings jsonb,p_actor_ref text,p_consent_scope_id text) returns uuid language plpgsql security definer set search_path=sourceenergy_one,pg_temp as $$
declare aid uuid; resolved_subject text; prior_id uuid; canonical jsonb:=jsonb_build_object('fear','integrity / fiduciary boundary / compliance','presence','mission and values alignment','wisdom','architecture and strategic design','knowledge','evidence, intelligence and data governance','understanding','integration and systems coherence','counsel','decision rights, review and authorization','might','controlled execution, deployment and completion'); ordered jsonb:='["fear","presence","wisdom","knowledge","understanding","counsel","might"]'::jsonb; k text; finding jsonb; ah text; dh text;
begin
 if nullif(btrim(p_subject_id),'') is null or nullif(btrim(p_object_type),'') is null or nullif(btrim(p_actor_ref),'') is null or nullif(btrim(p_consent_scope_id),'') is null then raise exception 'subject, object type, actor and consent scope required'; end if;
 resolved_subject:=sourceenergy_one.spirit_gate_object_subject(btrim(p_object_type),p_object_ref); if resolved_subject<>btrim(p_subject_id) then raise exception 'Spirit Gate subject does not match source object'; end if;
 if exists(select 1 from sourceenergy_one.spirit_gate_assessments where object_type=btrim(p_object_type) and object_ref=p_object_ref and gate_version='spirit-gate-v3' and status='human_confirmed') then raise exception 'Spirit Gate v3 already human-confirmed for object'; end if;
 select id into prior_id from sourceenergy_one.spirit_gate_assessments where object_type=btrim(p_object_type) and object_ref=p_object_ref and gate_version='spirit-gate-v3' order by created_at desc limit 1;
 if prior_id is not null and exists(select 1 from sourceenergy_one.spirit_gate_assessments where id=prior_id and status='assessed') then raise exception 'prior Spirit Gate v3 assessment requires review before revision'; end if;
 if p_dimension_findings is null or jsonb_typeof(p_dimension_findings)<>'object' then raise exception 'Spirit Gate v3 requires substantive dimension findings object'; end if;
 for k in select jsonb_array_elements_text(ordered) loop finding:=p_dimension_findings->k; if finding is null or jsonb_typeof(finding)<>'object' then raise exception 'Spirit Gate v3 missing finding for %',k; end if; if nullif(btrim(finding->>'assessment'),'') is null then raise exception 'Spirit Gate v3 % assessment required',k; end if; if nullif(btrim(finding->>'rationale'),'') is null then raise exception 'Spirit Gate v3 % rationale required',k; end if; if finding->>'disposition' not in ('aligned','hold') then raise exception 'Spirit Gate v3 % disposition must be aligned or hold',k; end if; end loop;
 dh:=encode(extensions.digest(convert_to(canonical::text,'UTF8'),'sha256'::text),'hex'); ah:=encode(extensions.digest(convert_to((jsonb_build_object('order',ordered,'mapping',canonical,'findings',p_dimension_findings))::text,'UTF8'),'sha256'::text),'hex');
 insert into sourceenergy_one.spirit_gate_assessments(subject_id,object_type,object_ref,gate_version,dimensions,dimension_findings,doctrine_mapping,doctrine_hash,assessment_hash,status,assessed_by_actor_ref,consent_scope_id,supersedes_assessment_id) values(btrim(p_subject_id),btrim(p_object_type),p_object_ref,'spirit-gate-v3',ordered,p_dimension_findings,canonical,dh,ah,'assessed',btrim(p_actor_ref),btrim(p_consent_scope_id),prior_id) returning id into aid;
 insert into sourceenergy_one.audit_events(correlation_id,subject_id,actor_id,event_type,object_type,object_ref,payload) values(gen_random_uuid(),btrim(p_subject_id),auth.uid(),'spirit_gate_v3_assessed','spirit_gate_assessment',aid::text,jsonb_build_object('source_object_type',btrim(p_object_type),'source_object_ref',p_object_ref,'gate_version','spirit-gate-v3','assessment_hash',ah,'doctrine_hash',dh,'supersedes_assessment_id',prior_id)); return aid;
end $$;
