create schema if not exists wim;

create table if not exists wim.economic_clusters (
  id bigint generated by default as identity primary key,
  canonical_code text not null unique,
  source_cluster_number integer,
  name text not null,
  cluster_scope text not null check (cluster_scope in ('traded','local')),
  source_system text not null default 'WIM Exchange / West Indies Trading Company',
  source_url text,
  status text not null default 'active' check (status in ('active','inactive','deprecated')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source_cluster_number, cluster_scope)
);

create table if not exists wim.economic_subclusters (
  id bigint generated by default as identity primary key,
  cluster_id bigint not null references wim.economic_clusters(id) on delete restrict,
  source_subcluster_number integer not null,
  canonical_code text not null unique,
  name text not null,
  source_url text,
  status text not null default 'active' check (status in ('active','inactive','deprecated')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(cluster_id, source_subcluster_number)
);

create table if not exists wim.organizations (
  id uuid primary key default gen_random_uuid(),
  setc_organization_id text unique,
  legal_name text not null,
  display_name text,
  organization_type text,
  jurisdiction_code text,
  website_url text,
  verification_status text not null default 'unverified' check (verification_status in ('unverified','pending','verified','restricted','suspended')),
  economic_status text not null default 'inactive' check (economic_status in ('inactive','active','restricted','suspended')),
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint wim_setc_org_id_format check (setc_organization_id is null or setc_organization_id ~ '^SETC-OID-[0-9a-f]{32}$')
);

create table if not exists wim.organization_cluster_memberships (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references wim.organizations(id) on delete cascade,
  cluster_id bigint references wim.economic_clusters(id) on delete restrict,
  subcluster_id bigint references wim.economic_subclusters(id) on delete restrict,
  role text not null default 'participant',
  capability_status text not null default 'declared' check (capability_status in ('declared','reviewed','verified','restricted')),
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(organization_id, cluster_id, subcluster_id, role),
  constraint wim_membership_scope check (cluster_id is not null or subcluster_id is not null)
);

create table if not exists wim.products_services (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references wim.organizations(id) on delete restrict,
  subcluster_id bigint references wim.economic_subclusters(id) on delete restrict,
  offering_type text not null check (offering_type in ('product','service','capability')),
  name text not null,
  description text,
  sku text,
  currency_code text,
  unit_price numeric,
  availability_status text not null default 'draft' check (availability_status in ('draft','available','limited','unavailable','retired')),
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists wim.markets (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  market_type text not null default 'geographic',
  country_code text,
  region_code text,
  description text,
  status text not null default 'active' check (status in ('active','inactive','restricted')),
  created_at timestamptz not null default now(),
  unique(name, country_code, region_code)
);

create table if not exists wim.trade_corridors (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  origin_market_id uuid not null references wim.markets(id) on delete restrict,
  destination_market_id uuid not null references wim.markets(id) on delete restrict,
  status text not null default 'proposed' check (status in ('proposed','active','restricted','inactive')),
  governance_notes text,
  created_at timestamptz not null default now(),
  unique(origin_market_id, destination_market_id, name),
  check (origin_market_id <> destination_market_id)
);

create table if not exists wim.opportunities (
  id uuid primary key default gen_random_uuid(),
  opportunity_type text not null check (opportunity_type in ('buy','sell','source','supply','procure','invest','partner','export','import','commercialize')),
  title text not null,
  description text,
  originating_organization_id uuid references wim.organizations(id) on delete restrict,
  market_id uuid references wim.markets(id) on delete restrict,
  cluster_id bigint references wim.economic_clusters(id) on delete restrict,
  subcluster_id bigint references wim.economic_subclusters(id) on delete restrict,
  currency_code text,
  target_value numeric,
  status text not null default 'draft' check (status in ('draft','open','matched','under_review','closed','cancelled','restricted')),
  opens_at timestamptz,
  closes_at timestamptz,
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists wim.transactions (
  id uuid primary key default gen_random_uuid(),
  opportunity_id uuid references wim.opportunities(id) on delete restrict,
  buyer_organization_id uuid references wim.organizations(id) on delete restrict,
  seller_organization_id uuid references wim.organizations(id) on delete restrict,
  transaction_class text not null default 'commercial',
  currency_code text,
  gross_amount numeric,
  settlement_status text not null default 'not_instructed' check (settlement_status in ('not_instructed','requested','pending','settled','failed','cancelled','restricted')),
  external_settlement_reference text,
  source_coin_request_reference text,
  source_coin_transaction_reference text,
  compliance_status text not null default 'not_assessed' check (compliance_status in ('not_assessed','review','allow','deny','restrict')),
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (buyer_organization_id is null or seller_organization_id is null or buyer_organization_id <> seller_organization_id)
);

create table if not exists wim.research_assets (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  source_url text,
  source_block_reference text,
  publication_date date,
  cluster_id bigint references wim.economic_clusters(id) on delete restrict,
  subcluster_id bigint references wim.economic_subclusters(id) on delete restrict,
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists wim.commercialization_projects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  lead_organization_id uuid references wim.organizations(id) on delete restrict,
  research_asset_id uuid references wim.research_assets(id) on delete restrict,
  opportunity_id uuid references wim.opportunities(id) on delete restrict,
  stage text not null default 'discovery' check (stage in ('discovery','validation','readiness','market_entry','scale','closed')),
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists wim.impact_metrics (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid references wim.transactions(id) on delete cascade,
  commercialization_project_id uuid references wim.commercialization_projects(id) on delete cascade,
  metric_code text not null,
  metric_name text not null,
  metric_value numeric,
  metric_unit text,
  measurement_period_start date,
  measurement_period_end date,
  methodology_version text,
  evidence_reference text,
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint wim_impact_parent check (transaction_id is not null or commercialization_project_id is not null)
);

create table if not exists wim.source_coin_events (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid references wim.transactions(id) on delete restrict,
  request_reference text not null unique,
  event_type text not null,
  source_coin_reference text,
  status text not null default 'requested' check (status in ('requested','accepted','rejected','settled','failed','cancelled')),
  economic_effect_authority text not null default 'Source Coin domain services',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table wim.economic_clusters enable row level security;
alter table wim.economic_subclusters enable row level security;
alter table wim.organizations enable row level security;
alter table wim.organization_cluster_memberships enable row level security;
alter table wim.products_services enable row level security;
alter table wim.markets enable row level security;
alter table wim.trade_corridors enable row level security;
alter table wim.opportunities enable row level security;
alter table wim.transactions enable row level security;
alter table wim.research_assets enable row level security;
alter table wim.commercialization_projects enable row level security;
alter table wim.impact_metrics enable row level security;
alter table wim.source_coin_events enable row level security;

revoke all on all tables in schema wim from anon, authenticated;
revoke all on all sequences in schema wim from anon, authenticated;

grant usage on schema wim to service_role;
grant all on all tables in schema wim to service_role;
grant all on all sequences in schema wim to service_role;

comment on schema wim is 'WIM Exchange bounded context: market access, trade, commerce, commercialization, and non-authoritative Source Coin integration references.';
comment on table wim.source_coin_events is 'Integration/reference records only. Source Coin dedicated ledger/domain services remain authoritative for economic execution.';
