drop view if exists ecology.execution_binding_readiness;
create view ecology.execution_binding_readiness as
with req as (select node_id,count(*) as requirement_count from ecology.execution_binding_requirements group by node_id),
bind as (select node_id,count(*) filter (where verification_status in ('verified_reference','source_verified')) as verified_binding_count,count(*) filter (where verification_status not in ('verified_reference','source_verified')) as nonverified_binding_count from ecology.execution_bindings group by node_id),
gate as (select node_id,count(*) as gate_count,count(*) filter (where gate_status in ('ready_reference','graduated_reference')) as ready_gate_count,count(*) filter (where gate_status='blocked') as blocked_gate_count from ecology.execution_gate_assessments group by node_id)
select n.canonical_code node_code,n.name node_name,n.domain_code,n.enablement_layer,n.flow_role,coalesce(req.requirement_count,0) requirement_count,coalesce(bind.verified_binding_count,0) verified_binding_count,coalesce(bind.nonverified_binding_count,0) nonverified_binding_count,coalesce(gate.ready_gate_count,0) ready_gate_count,coalesce(gate.blocked_gate_count,0) blocked_gate_count,coalesce(gate.gate_count,0) gate_count,case when coalesce(gate.blocked_gate_count,0)>0 then 'blocked' when coalesce(gate.gate_count,0)>0 and coalesce(gate.ready_gate_count,0)=coalesce(gate.gate_count,0) and coalesce(bind.verified_binding_count,0)>=coalesce(req.requirement_count,0) then 'execution_ready_reference' else 'not_execution_ready' end execution_readiness
from ecology.smart_specialization_nodes n left join req on req.node_id=n.id left join bind on bind.node_id=n.id left join gate on gate.node_id=n.id where n.node_type='specialization';

create table if not exists ecology.execution_evidence_inventory(id uuid primary key default gen_random_uuid(),authority_domain text not null,source_schema text not null,source_object text not null,available_records bigint not null default 0,evidence_posture text not null check (evidence_posture in ('empty','candidate_only','pending_verification','verified_reference_available','blocked_reference')),authority_boundary text not null,source_snapshot timestamptz not null default now(),provenance jsonb not null default '{}'::jsonb,unique(authority_domain,source_schema,source_object));
alter table ecology.execution_evidence_inventory enable row level security;
create policy execution_evidence_inventory_service_role_all on ecology.execution_evidence_inventory for all to service_role using (true) with check (true);
insert into ecology.execution_evidence_inventory(authority_domain,source_schema,source_object,available_records,evidence_posture,authority_boundary,provenance) values
('ENERGY','energy','projects',(select count(*) from energy.projects),'empty','Energy project registry is authoritative; no project may be inferred where registry is empty.',jsonb_build_object('rule','count_v1')),
('ENERGY','energy','capital_readiness_assessments',(select count(*) from energy.capital_readiness_assessments),'empty','Capital-readiness assessment is internal decision support and is not financing commitment.',jsonb_build_object('rule','count_v1')),
('LOGISTICS','rgl','projects',(select count(*) from rgl.projects),'empty','RGL project registry is authoritative; corridors alone do not establish project execution.',jsonb_build_object('rule','count_v1')),
('LOGISTICS','rgl','corridors',(select count(*) from rgl.corridors),case when (select count(*) from rgl.corridors)>0 then 'candidate_only' else 'empty' end,'Corridor records are routing references and do not establish node-specific execution.',jsonb_build_object('rule','count_v1')),
('SPATIAL','rgl','spatial_registry_links',(select count(*) from rgl.spatial_registry_links),case when exists(select 1 from rgl.spatial_registry_links where verification_status='verified') then 'verified_reference_available' when (select count(*) from rgl.spatial_registry_links)>0 then 'pending_verification' else 'empty' end,'Pending RGL spatial links do not satisfy EcoMatrix spatial verification gates.',jsonb_build_object('rule','status_v1')),
('SPATIAL','public','ssr_spatial_registry',(select count(*) from public.ssr_spatial_registry),case when (select count(*) from public.ssr_spatial_registry)>0 then 'verified_reference_available' else 'empty' end,'SSR is authoritative; RGL references do not substitute for authoritative registry entries.',jsonb_build_object('rule','count_v1')),
('COMMERCIALIZATION','wim','commercialization_projects',(select count(*) from wim.commercialization_projects),case when (select count(*) from wim.commercialization_projects)>0 then 'candidate_only' else 'empty' end,'Registration is required; presence is not an offer, award, sale, financing, or settlement.',jsonb_build_object('rule','count_v1')),
('COMMERCIALIZATION','wim','opportunities',(select count(*) from wim.opportunities),case when (select count(*) from wim.opportunities)>0 then 'candidate_only' else 'empty' end,'WIM opportunity records are non-binding references.',jsonb_build_object('rule','count_v1')),
('CAPITAL','capitalization','release_gates',(select count(*) from capitalization.release_gates),case when exists(select 1 from capitalization.release_gates where enabled=false) then 'blocked_reference' when exists(select 1 from capitalization.release_gates where enabled=true) then 'verified_reference_available' else 'empty' end,'Disabled release gates are explicit NO-GO controls and do not authorize deployment.',jsonb_build_object('rule','enabled_v1')),
('CAPITAL','capitalization','capital_sources',(select count(*) from capitalization.capital_sources),case when (select count(*) from capitalization.capital_sources)>0 then 'candidate_only' else 'empty' end,'Registry presence does not prove funds, custody, drawability, commitment, or settlement.',jsonb_build_object('rule','count_v1')),
('CAPITAL','capitalization','capital_facilities',(select count(*) from capitalization.capital_facilities),case when (select count(*) from capitalization.capital_facilities)>0 then 'candidate_only' else 'empty' end,'Facility records require evidence and do not independently establish available funding.',jsonb_build_object('rule','count_v1'))
on conflict (authority_domain,source_schema,source_object) do update set available_records=excluded.available_records,evidence_posture=excluded.evidence_posture,authority_boundary=excluded.authority_boundary,source_snapshot=now(),provenance=excluded.provenance;
create or replace view ecology.execution_evidence_dashboard as select authority_domain,source_schema,source_object,available_records,evidence_posture,authority_boundary,source_snapshot from ecology.execution_evidence_inventory order by authority_domain,source_schema,source_object;
