create table if not exists energy.measurement_sources (
  source_id uuid primary key default gen_random_uuid(),
  source_code text not null unique check (source_code ~ '^[A-Z0-9_-]{3,64}$'),
  source_type text not null check (source_type in ('UTILITY_METER','SCADA','BMS','EMS','INVERTER','BATTERY_MGMT','MANUAL_ATTESTATION','API','FILE_IMPORT','MODEL','FORECAST','OTHER')),
  source_name text not null check (length(btrim(source_name)) > 0),
  authority_state text not null default 'REFERENCE' check (authority_state in ('REFERENCE','PENDING_VERIFICATION','VERIFIED_SOURCE','AUTHORITATIVE_SOURCE','DISPUTED','ARCHIVED')),
  external_reference text,
  evidence_reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table energy.measurement_sources is 'Registry of operational measurement and modeling sources. MODEL and FORECAST sources are non-observed by definition and must not be treated as verified physical telemetry.';

create table if not exists energy.meters (
  meter_id uuid primary key default gen_random_uuid(),
  meter_code text not null unique check (meter_code ~ '^[A-Z0-9_-]{3,64}$'),
  source_id uuid references energy.measurement_sources(source_id) on delete set null,
  project_id uuid references energy.projects(project_id) on delete set null,
  asset_id uuid references energy.assets(asset_id) on delete set null,
  meter_type text not null check (meter_type in ('REVENUE','GENERATION','LOAD','NET','SUBMETER','STORAGE_CHARGE','STORAGE_DISCHARGE','FUEL','THERMAL','OTHER')),
  unit text not null,
  multiplier numeric not null default 1 check (multiplier > 0),
  meter_state text not null default 'REFERENCE' check (meter_state in ('REFERENCE','PENDING_VERIFICATION','VERIFIED','ACTIVE','INACTIVE','DISPUTED','RETIRED','ARCHIVED')),
  external_reference text,
  evidence_reference text,
  commissioned_at timestamptz,
  retired_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (project_id is not null or asset_id is not null)
);

create table if not exists energy.meter_readings (
  reading_id bigint generated by default as identity primary key,
  meter_id uuid not null references energy.meters(meter_id) on delete restrict,
  source_id uuid references energy.measurement_sources(source_id) on delete set null,
  reading_kind text not null check (reading_kind in ('OBSERVED','ESTIMATED','MODELED','FORECAST','CORRECTED')),
  interval_start timestamptz not null,
  interval_end timestamptz not null,
  quantity numeric not null,
  unit text not null,
  quality_state text not null default 'UNVERIFIED' check (quality_state in ('UNVERIFIED','SOURCE_VERIFIED','VALIDATED','ESTIMATED','MODELED','FORECAST','CORRECTED','DISPUTED','REJECTED')),
  external_reference text,
  evidence_reference text,
  correction_of_reading_id bigint references energy.meter_readings(reading_id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  observed_at timestamptz,
  created_at timestamptz not null default now(),
  check (interval_end > interval_start),
  check ((reading_kind = 'MODELED' and quality_state in ('MODELED','UNVERIFIED')) or
         (reading_kind = 'FORECAST' and quality_state in ('FORECAST','UNVERIFIED')) or
         (reading_kind not in ('MODELED','FORECAST')))
);
comment on table energy.meter_readings is 'Time-bounded meter readings with explicit observed/estimated/modeled/forecast classification. MODELED or FORECAST records cannot carry VALIDATED or SOURCE_VERIFIED quality.';

create table if not exists energy.generation_observations (
  observation_id bigint generated by default as identity primary key,
  project_id uuid references energy.projects(project_id) on delete set null,
  asset_id uuid references energy.assets(asset_id) on delete set null,
  source_id uuid references energy.measurement_sources(source_id) on delete set null,
  observation_kind text not null check (observation_kind in ('OBSERVED','ESTIMATED','MODELED','FORECAST','CORRECTED')),
  interval_start timestamptz not null,
  interval_end timestamptz not null,
  energy_mwh numeric check (energy_mwh is null or energy_mwh >= 0),
  average_power_mw numeric check (average_power_mw is null or average_power_mw >= 0),
  peak_power_mw numeric check (peak_power_mw is null or peak_power_mw >= 0),
  curtailment_mwh numeric check (curtailment_mwh is null or curtailment_mwh >= 0),
  availability_pct numeric check (availability_pct is null or (availability_pct >= 0 and availability_pct <= 100)),
  quality_state text not null default 'UNVERIFIED' check (quality_state in ('UNVERIFIED','SOURCE_VERIFIED','VALIDATED','ESTIMATED','MODELED','FORECAST','CORRECTED','DISPUTED','REJECTED')),
  evidence_reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (project_id is not null or asset_id is not null),
  check (interval_end > interval_start),
  check (energy_mwh is not null or average_power_mw is not null or peak_power_mw is not null or curtailment_mwh is not null or availability_pct is not null),
  check ((observation_kind = 'MODELED' and quality_state in ('MODELED','UNVERIFIED')) or
         (observation_kind = 'FORECAST' and quality_state in ('FORECAST','UNVERIFIED')) or
         (observation_kind not in ('MODELED','FORECAST')))
);

create table if not exists energy.storage_observations (
  observation_id bigint generated by default as identity primary key,
  asset_id uuid not null references energy.assets(asset_id) on delete restrict,
  project_id uuid references energy.projects(project_id) on delete set null,
  source_id uuid references energy.measurement_sources(source_id) on delete set null,
  observation_kind text not null check (observation_kind in ('OBSERVED','ESTIMATED','MODELED','FORECAST','CORRECTED')),
  observed_at timestamptz not null,
  state_of_charge_pct numeric check (state_of_charge_pct is null or (state_of_charge_pct >= 0 and state_of_charge_pct <= 100)),
  stored_energy_mwh numeric check (stored_energy_mwh is null or stored_energy_mwh >= 0),
  charge_power_mw numeric check (charge_power_mw is null or charge_power_mw >= 0),
  discharge_power_mw numeric check (discharge_power_mw is null or discharge_power_mw >= 0),
  available_capacity_mwh numeric check (available_capacity_mwh is null or available_capacity_mwh >= 0),
  cycle_count_equivalent numeric check (cycle_count_equivalent is null or cycle_count_equivalent >= 0),
  quality_state text not null default 'UNVERIFIED' check (quality_state in ('UNVERIFIED','SOURCE_VERIFIED','VALIDATED','ESTIMATED','MODELED','FORECAST','CORRECTED','DISPUTED','REJECTED')),
  evidence_reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (state_of_charge_pct is not null or stored_energy_mwh is not null or charge_power_mw is not null or discharge_power_mw is not null or available_capacity_mwh is not null or cycle_count_equivalent is not null),
  check ((observation_kind = 'MODELED' and quality_state in ('MODELED','UNVERIFIED')) or
         (observation_kind = 'FORECAST' and quality_state in ('FORECAST','UNVERIFIED')) or
         (observation_kind not in ('MODELED','FORECAST')))
);

create table if not exists energy.outage_events (
  outage_id uuid primary key default gen_random_uuid(),
  project_id uuid references energy.projects(project_id) on delete set null,
  asset_id uuid references energy.assets(asset_id) on delete set null,
  source_id uuid references energy.measurement_sources(source_id) on delete set null,
  outage_type text not null check (outage_type in ('PLANNED','FORCED','DERATE','GRID_CURTAILMENT','FUEL_CONSTRAINT','MAINTENANCE','COMMUNICATIONS','OTHER')),
  outage_state text not null default 'REPORTED' check (outage_state in ('REPORTED','PENDING_VERIFICATION','VERIFIED','ACTIVE','RESTORED','CLOSED','DISPUTED','REJECTED','ARCHIVED')),
  started_at timestamptz not null,
  ended_at timestamptz,
  unavailable_capacity_mw numeric check (unavailable_capacity_mw is null or unavailable_capacity_mw >= 0),
  cause_reference text,
  evidence_reference text,
  external_reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (project_id is not null or asset_id is not null),
  check (ended_at is null or ended_at > started_at)
);

create table if not exists energy.operational_performance_snapshots (
  snapshot_id uuid primary key default gen_random_uuid(),
  project_id uuid references energy.projects(project_id) on delete set null,
  asset_id uuid references energy.assets(asset_id) on delete set null,
  period_start timestamptz not null,
  period_end timestamptz not null,
  snapshot_kind text not null check (snapshot_kind in ('OBSERVED','ESTIMATED','MODELED','FORECAST','CORRECTED')),
  gross_generation_mwh numeric check (gross_generation_mwh is null or gross_generation_mwh >= 0),
  net_generation_mwh numeric check (net_generation_mwh is null or net_generation_mwh >= 0),
  energy_delivered_mwh numeric check (energy_delivered_mwh is null or energy_delivered_mwh >= 0),
  capacity_factor_pct numeric check (capacity_factor_pct is null or (capacity_factor_pct >= 0 and capacity_factor_pct <= 100)),
  availability_pct numeric check (availability_pct is null or (availability_pct >= 0 and availability_pct <= 100)),
  forced_outage_rate_pct numeric check (forced_outage_rate_pct is null or (forced_outage_rate_pct >= 0 and forced_outage_rate_pct <= 100)),
  round_trip_efficiency_pct numeric check (round_trip_efficiency_pct is null or (round_trip_efficiency_pct >= 0 and round_trip_efficiency_pct <= 100)),
  verification_state text not null default 'UNVERIFIED' check (verification_state in ('UNVERIFIED','SOURCE_VERIFIED','VALIDATED','ESTIMATED','MODELED','FORECAST','CORRECTED','DISPUTED','REJECTED')),
  evidence_reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (project_id is not null or asset_id is not null),
  check (period_end > period_start),
  check ((snapshot_kind = 'MODELED' and verification_state in ('MODELED','UNVERIFIED')) or
         (snapshot_kind = 'FORECAST' and verification_state in ('FORECAST','UNVERIFIED')) or
         (snapshot_kind not in ('MODELED','FORECAST')))
);
comment on table energy.operational_performance_snapshots is 'Operational performance summary only. It does not establish contract performance, invoice entitlement, settlement, REC issuance, regulatory compliance, or revenue recognition.';

create table if not exists energy.operations_evidence_links (
  evidence_link_id uuid primary key default gen_random_uuid(),
  entity_type text not null check (entity_type in ('METER','METER_READING','GENERATION_OBSERVATION','STORAGE_OBSERVATION','OUTAGE_EVENT','PERFORMANCE_SNAPSHOT')),
  entity_reference text not null,
  evidence_type text not null check (evidence_type in ('METER_FILE','SCADA_EXPORT','UTILITY_STATEMENT','OPERATOR_REPORT','API_RECEIPT','INSPECTION','PHOTO','CERTIFICATE','MODEL_INPUT','FORECAST_INPUT','OTHER')),
  evidence_reference text not null,
  verification_state text not null default 'REFERENCE' check (verification_state in ('REFERENCE','PENDING_VERIFICATION','VERIFIED','DISPUTED','REJECTED','ARCHIVED')),
  observed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(entity_type, entity_reference, evidence_reference)
);

alter table energy.measurement_sources enable row level security;
alter table energy.meters enable row level security;
alter table energy.meter_readings enable row level security;
alter table energy.generation_observations enable row level security;
alter table energy.storage_observations enable row level security;
alter table energy.outage_events enable row level security;
alter table energy.operational_performance_snapshots enable row level security;
alter table energy.operations_evidence_links enable row level security;

revoke all on energy.measurement_sources, energy.meters, energy.meter_readings, energy.generation_observations, energy.storage_observations, energy.outage_events, energy.operational_performance_snapshots, energy.operations_evidence_links from anon, authenticated;
grant all on energy.measurement_sources, energy.meters, energy.meter_readings, energy.generation_observations, energy.storage_observations, energy.outage_events, energy.operational_performance_snapshots, energy.operations_evidence_links to service_role;

create index if not exists idx_energy_meters_source on energy.meters(source_id) where source_id is not null;
create index if not exists idx_energy_meters_project on energy.meters(project_id) where project_id is not null;
create index if not exists idx_energy_meters_asset on energy.meters(asset_id) where asset_id is not null;
create index if not exists idx_energy_meter_readings_meter_time on energy.meter_readings(meter_id, interval_start desc);
create index if not exists idx_energy_meter_readings_source on energy.meter_readings(source_id) where source_id is not null;
create index if not exists idx_energy_meter_readings_correction on energy.meter_readings(correction_of_reading_id) where correction_of_reading_id is not null;
create index if not exists idx_energy_generation_project_time on energy.generation_observations(project_id, interval_start desc) where project_id is not null;
create index if not exists idx_energy_generation_asset_time on energy.generation_observations(asset_id, interval_start desc) where asset_id is not null;
create index if not exists idx_energy_generation_source on energy.generation_observations(source_id) where source_id is not null;
create index if not exists idx_energy_storage_asset_time on energy.storage_observations(asset_id, observed_at desc);
create index if not exists idx_energy_storage_project on energy.storage_observations(project_id) where project_id is not null;
create index if not exists idx_energy_storage_source on energy.storage_observations(source_id) where source_id is not null;
create index if not exists idx_energy_outage_project on energy.outage_events(project_id) where project_id is not null;
create index if not exists idx_energy_outage_asset on energy.outage_events(asset_id) where asset_id is not null;
create index if not exists idx_energy_outage_source on energy.outage_events(source_id) where source_id is not null;
create index if not exists idx_energy_perf_project_period on energy.operational_performance_snapshots(project_id, period_start desc) where project_id is not null;
create index if not exists idx_energy_perf_asset_period on energy.operational_performance_snapshots(asset_id, period_start desc) where asset_id is not null;
