create table if not exists sourcecubes.provider_runtime_readiness (
 provider_code text primary key references ecology.ssr_scientific_data_providers(provider_code), deployment_state text not null default 'UNKNOWN', credential_state text not null default 'UNKNOWN', upstream_runtime_state text not null default 'NOT_VALIDATED', evidence_state text not null default 'NO_RUNTIME_EVIDENCE', canonical_authority_state text not null default 'NONCANONICAL', last_validated_at timestamptz, evidence_reference text, notes text, updated_at timestamptz not null default now());
insert into sourcecubes.provider_runtime_readiness(provider_code,deployment_state,credential_state,upstream_runtime_state,evidence_state,canonical_authority_state,last_validated_at,evidence_reference,notes) values
('W3W','EDGE_ACTIVE','RUNTIME_CREDENTIAL_EVIDENCED','UPSTREAM_VALIDATED','API_TRANSACTION_VALIDATED','HORIZONTAL_ADDRESS_AUTHORITY',(select max(validated_at) from ecology.ssr_w3w_validation_log where validation_status='validated'),'ecology.ssr_w3w_validation_log','Validated What3Words transaction exists; horizontal address role only.'),
('OT-POINT','EDGE_ACTIVE','RUNTIME_CREDENTIAL_EVIDENCED','UPSTREAM_VALIDATED','API_TRANSACTION_VALIDATED','CONDITIONAL_EGM96_VERTICAL_AUTHORITY',(select max(updated_at) from ecology.ssr_anchor_candidate_registry where elevation_m_egm96 is not null),'NMIA OpenTopography SRTM_GL1 EGM96 evidence','Canonical Z only when response explicitly proves EGM96 compatibility.'),
('OT-SRTM15PLUS','EDGE_ACTIVE','CREDENTIAL_PATH_CONFIGURED_NOT_DATASET_PROVEN','DATASET_RUNTIME_NOT_VALIDATED','NO_DATASET_SPECIFIC_TRANSACTION','CONDITIONAL_EGM96_VERTICAL_AUTHORITY',null,'ssr-opentopography-elevation-resolver v7','Dataset-specific SRTM15Plus live call remains to be evidenced.'),
('OT-GEBCO','EDGE_ACTIVE','CREDENTIAL_PATH_CONFIGURED_NOT_DATASET_PROVEN','DATASET_RUNTIME_NOT_VALIDATED','NO_DATASET_SPECIFIC_TRANSACTION','DATUM_RECONCILIATION_REQUIRED',null,'ssr-opentopography-elevation-resolver v7','GEBCO via OpenTopography requires datum reconciliation.'),
('GEBCO-SOURCE','EDGE_ACTIVE','PUBLIC_NO_CREDENTIAL_REQUIRED','UPSTREAM_POINT_EXTRACTION_VALIDATED','POINT_OBSERVATION_RECORDED','DATUM_RECONCILIATION_REQUIRED',(select max(validated_at) from sourcecubes.provider_runtime_validation where provider_code='GEBCO-SOURCE'),'sourcecubes.vertical_evidence_observations / CEDA THREDDS OPeNDAP','GEBCO_2026 point extraction validated; no direct SSR Z authority.'),
('GOOGLE-ELEV','EDGE_ACTIVE','SECRET_PRESENCE_NOT_VALIDATED','UPSTREAM_RUNTIME_NOT_VALIDATED','NO_VALIDATED_TRANSACTION','CROSSCHECK_ONLY',null,'ssr-google-elevation-crosscheck v1','Secondary elevation crosscheck only.'),
('MAPBOX-TERRAIN','EDGE_ACTIVE','SECRET_PRESENCE_NOT_VALIDATED','UPSTREAM_RUNTIME_NOT_VALIDATED','NO_VALIDATED_TRANSACTION','VISUALIZATION_ONLY',null,'ssr-mapbox-terrain-visualization v1','Visualization only; never canonical SSR Z authority.')
on conflict(provider_code) do update set deployment_state=excluded.deployment_state,credential_state=excluded.credential_state,upstream_runtime_state=excluded.upstream_runtime_state,evidence_state=excluded.evidence_state,canonical_authority_state=excluded.canonical_authority_state,last_validated_at=excluded.last_validated_at,evidence_reference=excluded.evidence_reference,notes=excluded.notes,updated_at=now();
create or replace view sourcecubes.provider_runtime_readiness_dashboard as select r.provider_code,p.provider_name,p.domain,r.deployment_state,r.credential_state,r.upstream_runtime_state,r.evidence_state,r.canonical_authority_state,r.last_validated_at,r.evidence_reference,r.notes from sourcecubes.provider_runtime_readiness r join ecology.ssr_scientific_data_providers p using(provider_code) order by case r.provider_code when 'W3W' then 1 when 'OT-POINT' then 2 when 'OT-SRTM15PLUS' then 3 when 'OT-GEBCO' then 4 when 'GEBCO-SOURCE' then 5 when 'GOOGLE-ELEV' then 6 when 'MAPBOX-TERRAIN' then 7 else 99 end;
comment on table sourcecubes.provider_runtime_readiness is 'Controlled distinction between deployment, credential evidence, upstream runtime validation, evidence persistence, and canonical authority. Never infer one state from another.';
