create table if not exists wim.organization_market_memberships (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references wim.organizations(id) on delete cascade,
  market_id uuid not null references wim.markets(id) on delete cascade,
  market_role text not null check (market_role in ('buyer','seller','supplier','procurer','investor','partner','exporter','importer','commercializer','service_provider')),
  participation_status text not null default 'inactive' check (participation_status in ('inactive','active','restricted','suspended')),
  verification_status text not null default 'unverified' check (verification_status in ('unverified','pending','verified','restricted')),
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(organization_id, market_id, market_role)
);

create table if not exists wim.organization_trade_corridor_memberships (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references wim.organizations(id) on delete cascade,
  trade_corridor_id uuid not null references wim.trade_corridors(id) on delete cascade,
  corridor_role text not null check (corridor_role in ('shipper','consignee','carrier','broker','logistics_provider','buyer','seller','exporter','importer')),
  participation_status text not null default 'inactive' check (participation_status in ('inactive','active','restricted','suspended')),
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(organization_id, trade_corridor_id, corridor_role)
);

create index if not exists idx_wim_org_cluster_org on wim.organization_cluster_memberships(organization_id);
create index if not exists idx_wim_org_cluster_cluster on wim.organization_cluster_memberships(cluster_id);
create index if not exists idx_wim_org_market_org on wim.organization_market_memberships(organization_id);
create index if not exists idx_wim_org_market_market on wim.organization_market_memberships(market_id);
create index if not exists idx_wim_org_corridor_org on wim.organization_trade_corridor_memberships(organization_id);
create index if not exists idx_wim_org_corridor_corridor on wim.organization_trade_corridor_memberships(trade_corridor_id);

alter table wim.organization_market_memberships enable row level security;
alter table wim.organization_trade_corridor_memberships enable row level security;
revoke all on wim.organization_market_memberships from anon, authenticated;
revoke all on wim.organization_trade_corridor_memberships from anon, authenticated;
grant all on wim.organization_market_memberships to service_role;
grant all on wim.organization_trade_corridor_memberships to service_role;
grant usage, select on all sequences in schema wim to service_role;

create or replace function wim.enforce_organization_commercial_status()
returns trigger
language plpgsql
as $$
begin
  if new.economic_status in ('restricted','suspended','inactive') then
    update wim.organization_cluster_memberships
      set capability_status = case when new.economic_status='restricted' then 'restricted' else capability_status end
      where organization_id = new.id;
    update wim.organization_market_memberships
      set participation_status = case when new.economic_status='restricted' then 'restricted' else 'suspended' end,
          updated_at = now()
      where organization_id = new.id and participation_status = 'active';
    update wim.organization_trade_corridor_memberships
      set participation_status = case when new.economic_status='restricted' then 'restricted' else 'suspended' end,
          updated_at = now()
      where organization_id = new.id and participation_status = 'active';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_wim_org_commercial_status on wim.organizations;
create trigger trg_wim_org_commercial_status
after update of economic_status on wim.organizations
for each row when (old.economic_status is distinct from new.economic_status)
execute function wim.enforce_organization_commercial_status();

comment on table wim.organization_market_memberships is 'Commercial market-role projection for a WIM organization. Does not create or replace SETC institutional identity authority.';
comment on table wim.organization_trade_corridor_memberships is 'Organization participation projection within a governed WIM trade corridor.';
