create table if not exists wim.settlement_requests (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid not null references wim.transactions(id) on delete cascade,
  settlement_rail text not null check (settlement_rail in ('fiat_external','source_coin')),
  request_reference text not null unique,
  idempotency_key text not null unique,
  correlation_id text not null,
  causation_id text,
  requested_amount numeric,
  currency_code text,
  status text not null default 'requested' check (status in ('requested','pending','confirmed','failed','cancelled','restricted')),
  authoritative_confirmation_reference text,
  compliance_reference text,
  failure_code text,
  failure_detail text,
  requested_at timestamptz not null default now(),
  confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists wim.settlement_corrections (
  id uuid primary key default gen_random_uuid(),
  settlement_request_id uuid not null references wim.settlement_requests(id) on delete cascade,
  correction_type text not null,
  prior_state jsonb not null,
  corrected_state jsonb not null,
  reason text not null,
  evidence_reference text,
  created_at timestamptz not null default now()
);

create table if not exists wim.settlement_audit_events (
  id bigint generated by default as identity primary key,
  settlement_request_id uuid not null references wim.settlement_requests(id) on delete cascade,
  event_type text not null,
  event_payload jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

alter table wim.settlement_requests enable row level security;
alter table wim.settlement_corrections enable row level security;
alter table wim.settlement_audit_events enable row level security;
revoke all on wim.settlement_requests, wim.settlement_corrections, wim.settlement_audit_events from anon, authenticated;
grant all on wim.settlement_requests, wim.settlement_corrections, wim.settlement_audit_events to service_role;
grant usage, select on all sequences in schema wim to service_role;

create index if not exists idx_wim_settlement_requests_txn on wim.settlement_requests(transaction_id);
create index if not exists idx_wim_settlement_requests_status on wim.settlement_requests(settlement_rail,status);
create index if not exists idx_wim_settlement_audit_request on wim.settlement_audit_events(settlement_request_id,occurred_at);

create or replace function wim.enforce_settlement_request()
returns trigger
language plpgsql
as $$
begin
  if btrim(new.request_reference) = '' or btrim(new.idempotency_key) = '' or btrim(new.correlation_id) = '' then
    raise exception 'request_reference, idempotency_key and correlation_id are required';
  end if;
  if new.requested_amount is not null and new.requested_amount < 0 then
    raise exception 'requested amount cannot be negative';
  end if;
  if new.status = 'confirmed' then
    if new.authoritative_confirmation_reference is null or btrim(new.authoritative_confirmation_reference) = '' then
      raise exception 'confirmed settlement requires authoritative confirmation reference';
    end if;
    if new.confirmed_at is null then new.confirmed_at := now(); end if;
  end if;
  if new.settlement_rail = 'source_coin' and new.status = 'confirmed' then
    if new.authoritative_confirmation_reference !~ '^SC-' then
      raise exception 'Source Coin confirmation must originate from authoritative Source Coin domain reference';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_wim_settlement_request on wim.settlement_requests;
create trigger trg_wim_settlement_request
before insert or update on wim.settlement_requests
for each row execute function wim.enforce_settlement_request();

create or replace function wim.audit_settlement_request()
returns trigger
language plpgsql
as $$
begin
  if tg_op='INSERT' then
    insert into wim.settlement_audit_events(settlement_request_id,event_type,event_payload)
    values(new.id,'settlement.requested',jsonb_build_object('rail',new.settlement_rail,'status',new.status,'request_reference',new.request_reference));
  elsif old.status is distinct from new.status then
    insert into wim.settlement_audit_events(settlement_request_id,event_type,event_payload)
    values(new.id,'settlement.status_changed',jsonb_build_object('from',old.status,'to',new.status,'rail',new.settlement_rail));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_wim_settlement_audit on wim.settlement_requests;
create trigger trg_wim_settlement_audit
after insert or update on wim.settlement_requests
for each row execute function wim.audit_settlement_request();

comment on table wim.settlement_requests is 'WIM settlement orchestration requests. Finality is conferred only by the authoritative external fiat rail or Source Coin domain confirmation.';
comment on column wim.settlement_requests.idempotency_key is 'Unique retry key preventing duplicate economic execution requests.';
comment on table wim.settlement_corrections is 'Append-only compensating correction evidence; not destructive mutation of authoritative settlement history.';
