-- HEI-BUILD-008 — Institutional Infrastructure, Real Assets, Energy & Campus Development Core
-- Institution retains ownership, project approval, financing and contracting authority.

CREATE TABLE public.hei_capital_projects (
 id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 organization_oid text NOT NULL REFERENCES public.setc_organizations(oid),
 project_reference text NOT NULL UNIQUE,
 name text NOT NULL,
 project_type text NOT NULL CHECK (project_type IN ('ACADEMIC','RESEARCH','HOUSING','HEALTHCARE','ENERGY','DIGITAL','WATER','TRANSPORT','LOGISTICS','RESILIENCE','OTHER')),
 status text NOT NULL DEFAULT 'CONCEPT' CHECK (status IN ('CONCEPT','PLANNING','DILIGENCE','APPROVED','PROCUREMENT','FINANCING','CONSTRUCTION','OPERATING','SUSPENDED','CLOSED')),
 governance_reference text,
 evidence_reference text,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.hei_project_assets (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,capital_project_id bigint NOT NULL REFERENCES public.hei_capital_projects(id) ON DELETE CASCADE,asset_reference text NOT NULL UNIQUE,asset_type text NOT NULL CHECK (asset_type IN ('LAND','BUILDING','ENERGY_SYSTEM','DATA_INFRASTRUCTURE','WATER_SYSTEM','TRANSPORT_ASSET','EQUIPMENT','OTHER')),ownership_state text NOT NULL DEFAULT 'PROPOSED' CHECK (ownership_state IN ('PROPOSED','INSTITUTION_OWNED','LEASED','JV_OWNED','THIRD_PARTY','TRANSFER_PENDING')),title_or_lease_reference text,evidence_reference text);
CREATE TABLE public.hei_project_budgets (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,capital_project_id bigint NOT NULL REFERENCES public.hei_capital_projects(id),budget_reference text NOT NULL UNIQUE,total_budget numeric(20,4) NOT NULL CHECK (total_budget >= 0),currency_code text NOT NULL CHECK (currency_code ~ '^[A-Z]{3}$'),status text NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','REVIEW','APPROVED','REVISED','CLOSED')),authority_reference text,evidence_reference text);
CREATE TABLE public.hei_project_financing_sources (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,capital_project_id bigint NOT NULL REFERENCES public.hei_capital_projects(id),source_reference text NOT NULL UNIQUE,source_type text NOT NULL CHECK (source_type IN ('INSTITUTIONAL_CASH','GRANT','PHILANTHROPY','BOND','LOAN','LEASE','P3','MISSION_CAPITAL','ENERGY_SAVINGS','OTHER')),committed_amount numeric(20,4) CHECK (committed_amount IS NULL OR committed_amount >= 0),currency_code text CHECK (currency_code IS NULL OR currency_code ~ '^[A-Z]{3}$'),commitment_state text NOT NULL DEFAULT 'PROPOSED' CHECK (commitment_state IN ('PROPOSED','DOCUMENTED','APPROVED','COMMITTED','FUNDED','CANCELLED','CLOSED')),authority_reference text,external_reference text,evidence_reference text);
CREATE TABLE public.hei_project_milestones (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,capital_project_id bigint NOT NULL REFERENCES public.hei_capital_projects(id) ON DELETE CASCADE,milestone_reference text NOT NULL UNIQUE,milestone_type text NOT NULL CHECK (milestone_type IN ('DESIGN','PERMIT','FINANCIAL_CLOSE','PROCUREMENT','NOTICE_TO_PROCEED','CONSTRUCTION','COMMISSIONING','OPERATIONS','OTHER')),status text NOT NULL DEFAULT 'PLANNED' CHECK (status IN ('PLANNED','IN_PROGRESS','COMPLETED','DELAYED','BLOCKED','CANCELLED')),planned_at timestamptz,completed_at timestamptz,evidence_reference text);
CREATE TABLE public.hei_project_participants (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,capital_project_id bigint NOT NULL REFERENCES public.hei_capital_projects(id) ON DELETE CASCADE,organization_oid text NOT NULL REFERENCES public.setc_organizations(oid),participant_role text NOT NULL CHECK (participant_role IN ('OWNER','DEVELOPER','DESIGNER','CONTRACTOR','ENERGY_PARTNER','TECHNOLOGY_PARTNER','FINANCE_PARTNER','OPERATOR','PUBLIC_SECTOR','OTHER')),status text NOT NULL DEFAULT 'PROPOSED' CHECK (status IN ('PROPOSED','DILIGENCE','APPROVED','ACTIVE','SUSPENDED','WITHDRAWN','COMPLETED')),authority_reference text,evidence_reference text,UNIQUE(capital_project_id,organization_oid,participant_role));
CREATE TABLE public.hei_project_external_links (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,capital_project_id bigint NOT NULL REFERENCES public.hei_capital_projects(id) ON DELETE CASCADE,link_type text NOT NULL CHECK (link_type IN ('PROCUREMENT','WIM','SOURCEENERGY_GLOBAL','ENERGY','LOGISTICS','FINANCE','ERP','OTHER')),external_reference text NOT NULL,status text NOT NULL DEFAULT 'REFERENCE_ONLY' CHECK (status IN ('REFERENCE_ONLY','ACTIVE','SUSPENDED','RETIRED')),evidence_reference text,UNIQUE(capital_project_id,link_type,external_reference));
CREATE OR REPLACE FUNCTION public.hei_validate_project_financing() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE project_state text; BEGIN IF NEW.commitment_state IN ('APPROVED','COMMITTED','FUNDED','CLOSED') THEN SELECT status INTO project_state FROM public.hei_capital_projects WHERE id=NEW.capital_project_id; IF project_state NOT IN ('APPROVED','PROCUREMENT','FINANCING','CONSTRUCTION','OPERATING','CLOSED') THEN RAISE EXCEPTION 'approved capital project required'; END IF; IF NEW.authority_reference IS NULL OR btrim(NEW.authority_reference)='' THEN RAISE EXCEPTION 'institutional financing authority required'; END IF; IF NEW.evidence_reference IS NULL OR btrim(NEW.evidence_reference)='' THEN RAISE EXCEPTION 'financing evidence required'; END IF; END IF; RETURN NEW; END $$;
CREATE TRIGGER hei_project_financing_gate BEFORE INSERT OR UPDATE ON public.hei_project_financing_sources FOR EACH ROW EXECUTE FUNCTION public.hei_validate_project_financing();
CREATE OR REPLACE FUNCTION public.hei_validate_project_operating_state() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.status='OPERATING' AND NOT EXISTS (SELECT 1 FROM public.hei_project_milestones m WHERE m.capital_project_id=NEW.id AND m.milestone_type='COMMISSIONING' AND m.status='COMPLETED' AND m.evidence_reference IS NOT NULL AND btrim(m.evidence_reference)<>'') THEN RAISE EXCEPTION 'completed evidenced commissioning milestone required'; END IF; RETURN NEW; END $$;
CREATE TRIGGER hei_project_operating_gate BEFORE INSERT OR UPDATE ON public.hei_capital_projects FOR EACH ROW EXECUTE FUNCTION public.hei_validate_project_operating_state();
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['hei_capital_projects','hei_project_assets','hei_project_budgets','hei_project_financing_sources','hei_project_milestones','hei_project_participants','hei_project_external_links'] LOOP EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated',t); EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)',t||'_service_role_all',t); END LOOP; END $$;
COMMENT ON TABLE public.hei_capital_projects IS 'Institution-controlled campus and real-asset project registry; project records do not themselves convey ownership, financing, permits or construction authority.';
COMMENT ON TABLE public.hei_project_financing_sources IS 'Financing commitment evidence layer; proposed or documented financing is not cash, settlement, custody or financial close.';
COMMENT ON TABLE public.hei_project_external_links IS 'Reference-only integration boundary to procurement, WIM, SourceEnergy Global, energy, logistics, finance and ERP systems.';
