create or replace function sourceenergy_one.spirit_gate_object_subject(p_object_type text,p_object_ref uuid) returns text language plpgsql security definer set search_path=sourceenergy_one,pg_temp as $$ declare s text; begin case p_object_type when 'living_purpose_journal_entry' then select subject_id into s from sourceenergy_one.living_purpose_journal_entries where id=p_object_ref; when 'knowledge_artifact' then select subject_id into s from sourceenergy_one.knowledge_artifacts where id=p_object_ref; when 'knowledge_insight' then select subject_id into s from sourceenergy_one.knowledge_insights where id=p_object_ref; when 'purpose_reflection_synthesis' then select subject_id into s from sourceenergy_one.purpose_reflection_syntheses where id=p_object_ref; when 'impact_report' then select subject_id into s from sourceenergy_one.impact_reports where id=p_object_ref; when 'genesis_approval' then select ir.subject_id into s from sourceenergy_one.genesis_approvals ga join sourceenergy_one.impact_reports ir on ir.id=ga.impact_report_id where ga.id=p_object_ref; when 'genesis_evolution_nomination' then select subject_id into s from sourceenergy_one.genesis_evolution_nominations where id=p_object_ref; else raise exception 'unsupported Spirit Gate object type: %',p_object_type; end case; if s is null then raise exception 'Spirit Gate source object not found'; end if; return s; end $$;

create or replace function sourceenergy_one.assess_spirit_gate(p_subject_id text,p_object_type text,p_object_ref uuid,p_dimensions jsonb,p_actor_ref text,p_consent_scope_id text) returns uuid language plpgsql security definer set search_path=sourceenergy_one,pg_temp as $$ declare aid uuid; h text; expected text[]:=array['fear','presence','wisdom','knowledge','understanding','counsel','might']; k text; i int:=0; resolved_subject text; begin if nullif(btrim(p_subject_id),'') is null or nullif(btrim(p_object_type),'') is null or nullif(btrim(p_actor_ref),'') is null or nullif(btrim(p_consent_scope_id),'') is null then raise exception 'subject, object type, actor and consent scope required'; end if; if p_object_ref is null then raise exception 'object_ref required'; end if; resolved_subject:=sourceenergy_one.spirit_gate_object_subject(btrim(p_object_type),p_object_ref); if resolved_subject<>btrim(p_subject_id) then raise exception 'Spirit Gate subject does not match source object'; end if; if p_dimensions is null or jsonb_typeof(p_dimensions)<>'array' or jsonb_array_length(p_dimensions)<>7 then raise exception 'Spirit Gate requires exactly seven ordered dimensions'; end if; for k in select jsonb_array_elements_text(p_dimensions) loop i:=i+1; if lower(k)<>expected[i] then raise exception 'invalid Spirit Gate order at position %: expected %',i,expected[i]; end if; end loop; h:=encode(extensions.digest(convert_to(p_dimensions::text,'UTF8'),'sha256'::text),'hex'); insert into sourceenergy_one.spirit_gate_assessments(subject_id,object_type,object_ref,dimensions,assessment_hash,assessed_by_actor_ref,consent_scope_id) values(btrim(p_subject_id),btrim(p_object_type),p_object_ref,p_dimensions,h,btrim(p_actor_ref),btrim(p_consent_scope_id)) returning id into aid; insert into sourceenergy_one.audit_events(correlation_id,subject_id,actor_id,event_type,object_type,object_ref,payload) values(gen_random_uuid(),btrim(p_subject_id),auth.uid(),'spirit_gate_assessed','spirit_gate_assessment',aid::text,jsonb_build_object('source_object_type',btrim(p_object_type),'source_object_ref',p_object_ref,'gate_version','spirit-gate-v1','assessment_hash',h)); return aid; end $$;

create or replace function sourceenergy_one.enforce_spirit_gate_on_knowledge_transition() returns trigger language plpgsql set search_path=sourceenergy_one,pg_temp as $$ declare x uuid; begin foreach x in array new.evidence_artifact_ids loop perform sourceenergy_one.require_spirit_gate('knowledge_artifact',x); end loop; return new; end $$;
drop trigger if exists knowledge_transition_spirit_gate_trg on sourceenergy_one.knowledge_transitions;
create trigger knowledge_transition_spirit_gate_trg before insert on sourceenergy_one.knowledge_transitions for each row execute function sourceenergy_one.enforce_spirit_gate_on_knowledge_transition();

create or replace function sourceenergy_one.enforce_spirit_gate_on_knowledge_insight_insert() returns trigger language plpgsql set search_path=sourceenergy_one,pg_temp as $$ declare x uuid; begin foreach x in array new.source_artifact_ids loop perform sourceenergy_one.require_spirit_gate('knowledge_artifact',x); end loop; return new; end $$;
drop trigger if exists knowledge_insight_source_spirit_gate_trg on sourceenergy_one.knowledge_insights;
create trigger knowledge_insight_source_spirit_gate_trg before insert on sourceenergy_one.knowledge_insights for each row execute function sourceenergy_one.enforce_spirit_gate_on_knowledge_insight_insert();

create or replace function sourceenergy_one.enforce_spirit_gate_on_knowledge_insight_review() returns trigger language plpgsql set search_path=sourceenergy_one,pg_temp as $$ begin if old.authority_status='counsel' and new.authority_status='human_confirmed' then perform sourceenergy_one.require_spirit_gate('knowledge_insight',new.id); end if; return new; end $$;
drop trigger if exists knowledge_insight_review_spirit_gate_trg on sourceenergy_one.knowledge_insights;
create trigger knowledge_insight_review_spirit_gate_trg before update on sourceenergy_one.knowledge_insights for each row execute function sourceenergy_one.enforce_spirit_gate_on_knowledge_insight_review();

create or replace function sourceenergy_one.enforce_spirit_gate_on_reflection_insert() returns trigger language plpgsql set search_path=sourceenergy_one,pg_temp as $$ declare x uuid; begin foreach x in array new.source_entry_ids loop if exists(select 1 from sourceenergy_one.living_purpose_journal_entries where id=x) then perform sourceenergy_one.require_spirit_gate('living_purpose_journal_entry',x); elsif exists(select 1 from sourceenergy_one.knowledge_artifacts where id=x) then perform sourceenergy_one.require_spirit_gate('knowledge_artifact',x); else raise exception 'reflection evidence object not recognized for Spirit Gate: %',x; end if; end loop; return new; end $$;
drop trigger if exists purpose_reflection_source_spirit_gate_trg on sourceenergy_one.purpose_reflection_syntheses;
create trigger purpose_reflection_source_spirit_gate_trg before insert on sourceenergy_one.purpose_reflection_syntheses for each row execute function sourceenergy_one.enforce_spirit_gate_on_reflection_insert();

create or replace function sourceenergy_one.enforce_spirit_gate_on_reflection_review() returns trigger language plpgsql set search_path=sourceenergy_one,pg_temp as $$ begin if old.human_review_status='pending' and new.human_review_status='confirmed' then perform sourceenergy_one.require_spirit_gate('purpose_reflection_synthesis',new.id); end if; return new; end $$;
drop trigger if exists purpose_reflection_review_spirit_gate_trg on sourceenergy_one.purpose_reflection_syntheses;
create trigger purpose_reflection_review_spirit_gate_trg before update on sourceenergy_one.purpose_reflection_syntheses for each row execute function sourceenergy_one.enforce_spirit_gate_on_reflection_review();

create or replace function sourceenergy_one.enforce_spirit_gate_on_evolution_nomination() returns trigger language plpgsql set search_path=sourceenergy_one,pg_temp as $$ begin perform sourceenergy_one.require_spirit_gate('purpose_reflection_synthesis',new.reflection_id); return new; end $$;
drop trigger if exists genesis_evolution_spirit_gate_trg on sourceenergy_one.genesis_evolution_nominations;
create trigger genesis_evolution_spirit_gate_trg before insert on sourceenergy_one.genesis_evolution_nominations for each row execute function sourceenergy_one.enforce_spirit_gate_on_evolution_nomination();

create or replace function sourceenergy_one.enforce_spirit_gate_on_genesis_insert() returns trigger language plpgsql set search_path=sourceenergy_one,pg_temp as $$ begin perform sourceenergy_one.require_spirit_gate('impact_report',new.impact_report_id); perform sourceenergy_one.require_spirit_gate('genesis_approval',new.approval_id); return new; end $$;
drop trigger if exists genesis_package_spirit_gate_trg on sourceenergy_one.genesis_packages;
create trigger genesis_package_spirit_gate_trg before insert on sourceenergy_one.genesis_packages for each row execute function sourceenergy_one.enforce_spirit_gate_on_genesis_insert();

revoke all on function sourceenergy_one.spirit_gate_object_subject(text,uuid) from public,anon,authenticated;
grant execute on function sourceenergy_one.spirit_gate_object_subject(text,uuid) to service_role;
