insert into sourcecubes.cube_evidence_bindings(cube_uid,domain,evidence_role,provider_code,source_schema,source_table,source_record_id,observed_at,requested_latitude,requested_longitude,grid_latitude,grid_longitude,observed_z_index,spatial_association_state,vertical_authority_state,canonical_identity_authority,physical_impact_authority,official_warning_authority,evidence_reference,evidence_payload)
select cb.cube_uid,'LAND','CANONICAL_SURFACE_ELEVATION_EVIDENCE','OT-POINT','ecology','ssr_anchor_candidate_registry',c.id::text,c.updated_at,c.latitude,c.longitude,c.latitude,c.longitude,c.z_index,'EXACT_ANCHOR_COORDINATE','CANONICAL_EGM96_Z_EVIDENCE',false,false,false,coalesce(c.elevation_evidence_reference,c.source_reference),jsonb_build_object('elevation_m_egm96',c.elevation_m_egm96,'z_index',c.z_index,'z_assignment_standard',c.z_assignment_standard,'role','evidence_only_canonical_identity_remains_anchor_cube')
from ecology.ssr_anchor_candidate_registry c join sourcecubes.cube_bindings cb on cb.anchor_candidate_id=c.id
where c.infrastructure_name='Norman Manley International Airport' and cb.binding_status='AUTHORITATIVE_ACTIVE' and c.elevation_m_egm96 is not null
and not exists(select 1 from sourcecubes.cube_evidence_bindings e where e.cube_uid=cb.cube_uid and e.domain='LAND' and e.provider_code='OT-POINT' and e.source_record_id=c.id::text);
create table if not exists sourcecubes.subsurface_evidence_queue(queue_id uuid primary key default gen_random_uuid(),cube_uid text not null,anchor_tile_id text not null,latitude double precision not null,longitude double precision not null,evidence_target text not null,authority_policy text not null default 'OBSERVATIONAL_ONLY_NO_CANONICAL_IDENTITY_AUTHORITY',queue_state text not null default 'EVIDENCE_SOURCE_REQUIRED',evidence_reference text,created_at timestamptz not null default now(),unique(cube_uid,evidence_target));
insert into sourcecubes.subsurface_evidence_queue(cube_uid,anchor_tile_id,latitude,longitude,evidence_target,queue_state,evidence_reference) select cube_uid,anchor_tile_id,latitude,longitude,'SUBSURFACE_GEOLOGY_OR_BOREHOLE_EVIDENCE','EVIDENCE_SOURCE_REQUIRED','No authoritative subsurface observation is currently registered for this AnchorTile; do not infer geology from surface/bathymetry evidence.' from sourcecubes.cube_bindings where binding_status='AUTHORITATIVE_ACTIVE' and anchor_tile_id='SSR-411.IX-01' on conflict(cube_uid,evidence_target) do nothing;
create or replace view sourcecubes.domain_completion_dashboard as select cb.cube_uid,cb.anchor_tile_id,cb.canonical_address,count(*) filter(where e.domain='AIR') as air_count,count(*) filter(where e.domain='LAND') as land_count,count(*) filter(where e.domain='SEA') as sea_count,count(*) filter(where e.domain='SUBSURFACE') as subsurface_count,case when count(*) filter(where e.domain='AIR')>0 then 'EVIDENCE_ACTIVE' else 'EVIDENCE_REQUIRED' end air_state,case when count(*) filter(where e.domain='LAND')>0 then 'EVIDENCE_ACTIVE' else 'EVIDENCE_REQUIRED' end land_state,case when count(*) filter(where e.domain='SEA')>0 then 'EVIDENCE_ACTIVE' else 'EVIDENCE_REQUIRED' end sea_state,case when count(*) filter(where e.domain='SUBSURFACE')>0 then 'EVIDENCE_ACTIVE' else 'EVIDENCE_REQUIRED' end subsurface_state from sourcecubes.cube_bindings cb left join sourcecubes.cube_evidence_bindings e on e.cube_uid=cb.cube_uid where cb.binding_status='AUTHORITATIVE_ACTIVE' group by cb.cube_uid,cb.anchor_tile_id,cb.canonical_address;
comment on table sourcecubes.subsurface_evidence_queue is 'Fail-closed queue for genuine subsurface geology/borehole/geotechnical evidence. Surface elevation and bathymetry must not be relabeled as subsurface evidence.';
