insert into wim.economic_clusters (canonical_code, source_cluster_number, name, cluster_scope, source_url) values
('WIM-T01',1,'Transportation and Logistics','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T02',2,'Hospitality and Tourism','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T03',3,'Food, Beverage and Tobacco','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T04',4,'Natural Resource and Industrial Products','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T05',5,'Agriculture','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T06',6,'Construction','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T07',7,'Financial Services','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T08',8,'Power and Utilities','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T09',9,'Education and Research','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T10',10,'Forest Products','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T11',11,'Medical Devices','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T12',12,'Jewelry and Precious Metals','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T13',13,'Biopharmaceuticals','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T14',14,'Production Technology and Heavy Machinery','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T15',15,'Upstream Metal Manufacturing','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T16',16,'Downstream Metal Products','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T17',17,'Oil and Gas Production and Transportation','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T18',18,'Furniture','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T19',19,'Business Services','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T20',20,'Marketing, Design and Publishing','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T21',21,'Performing Arts','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T22',22,'Vulcanized and Fired Materials','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T23',23,'Information Technology and Analytical Instruments','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T24',24,'Textile Manufacturing','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T25',25,'Apparel','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T26',26,'Lighting and Electrical Equipment','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T27',27,'Communications Equipment and Services','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T28',28,'Distribution and Electronic Commerce','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T29',29,'Plastics','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T30',30,'Leather and Related Products','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T31',31,'Insurance Services','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T32',32,'Printing Services','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T33',33,'Environmental Services','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T34',34,'Video Production and Distribution','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T35',35,'Music and Sound Recording','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T36',36,'Recreational and Small Electric Goods','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T37',37,'Automotive','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T38',38,'Aerospace and Defense','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T39',39,'Trailers, Motor Homes and Appliances','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T40',40,'Metal Mining','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T41',41,'Tobacco','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T42',42,'Footwear','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T43',43,'Livestock Processing','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T44',44,'Water Transportation','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T45',45,'Fishing and Fishing Products','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T46',46,'Coal Mining','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T47',47,'Oil and Gas Products and Services','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T48',48,'Paper and Packaging','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T49',49,'Transportation and Logistics','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-T50',50,'Hospitality and Tourism','traded','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L01',1,'Local Food and Beverage Processing and Distribution','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L02',2,'Local Hospitality Establishments','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L03',3,'Local Commercial Services','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L04',4,'Local Real Estate, Construction and Development','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L05',5,'Local Household Goods and Services','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L06',6,'Local Motor Vehicle Products and Services','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L07',7,'Local Health Services','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L08',8,'Local Financial Services','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L09',9,'Local Community and Civic Organizations','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L10',10,'Local Education and Training','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L11',11,'Local Personal Services','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L12',12,'Local Entertainment and Media','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L13',13,'Local Retailing of Clothing and General Merchandise','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L14',14,'Local Industrial Products and Services','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L15',15,'Local Logistical Services','local','https://wimexchange.com/the-west-indies-trading-company/'),
('WIM-L16',16,'Local Utilities','local','https://wimexchange.com/the-west-indies-trading-company/')
on conflict (canonical_code) do nothing;
