alter table wim.transactions
  add column if not exists trade_corridor_id uuid references wim.trade_corridors(id) on delete restrict,
  add column if not exists trade_status text not null default 'initiated' check (trade_status in ('initiated','documentation','compliance_review','approved','in_transit','delivered','reconciled','exception','cancelled','restricted')),
  add column if not exists compliance_reference text,
  add column if not exists logistics_reference text,
  add column if not exists import_export_evidence_reference text,
  add column if not exists reconciled_at timestamptz,
  add column if not exists exception_reason text;

create table if not exists wim.trade_compliance_checkpoints (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid not null references wim.transactions(id) on delete cascade,
  checkpoint_type text not null check (checkpoint_type in ('counterparty','corridor','documentation','sanctions','aml_kyc','customs','export_control','other')),
  status text not null default 'pending' check (status in ('pending','passed','failed','restricted','not_applicable')),
  evidence_reference text,
  reviewed_at timestamptz,
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(transaction_id, checkpoint_type)
);

create table if not exists wim.trade_logistics_references (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid not null references wim.transactions(id) on delete cascade,
  reference_type text not null check (reference_type in ('shipment','carrier','warehouse','cash_logistics','customs','insurance','tracking','other')),
  external_reference text not null,
  provider_name text,
  evidence_reference text,
  authority_boundary text not null default 'reference_only_no_banking_or_custody_authority',
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(transaction_id, reference_type, external_reference)
);

create table if not exists wim.trade_corrections (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid not null references wim.transactions(id) on delete cascade,
  correction_type text not null,
  prior_state jsonb not null,
  corrected_state jsonb not null,
  reason text not null,
  evidence_reference text,
  created_at timestamptz not null default now()
);

create table if not exists wim.trade_audit_events (
  id bigint generated by default as identity primary key,
  transaction_id uuid not null references wim.transactions(id) on delete cascade,
  event_type text not null,
  event_payload jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

alter table wim.trade_compliance_checkpoints enable row level security;
alter table wim.trade_logistics_references enable row level security;
alter table wim.trade_corrections enable row level security;
alter table wim.trade_audit_events enable row level security;
revoke all on wim.trade_compliance_checkpoints, wim.trade_logistics_references, wim.trade_corrections, wim.trade_audit_events from anon, authenticated;
grant all on wim.trade_compliance_checkpoints, wim.trade_logistics_references, wim.trade_corrections, wim.trade_audit_events to service_role;
grant usage, select on all sequences in schema wim to service_role;

create index if not exists idx_wim_transactions_trade_status on wim.transactions(trade_status);
create index if not exists idx_wim_transactions_corridor on wim.transactions(trade_corridor_id);
create index if not exists idx_wim_trade_compliance_txn on wim.trade_compliance_checkpoints(transaction_id,status);
create index if not exists idx_wim_trade_logistics_txn on wim.trade_logistics_references(transaction_id);
create index if not exists idx_wim_trade_audit_txn on wim.trade_audit_events(transaction_id,occurred_at);

create or replace function wim.enforce_trade_progression()
returns trigger
language plpgsql
as $$
declare
  corridor_status text;
  failed_checks integer;
begin
  if new.buyer_organization_id is not null and new.seller_organization_id is not null and new.buyer_organization_id = new.seller_organization_id then
    raise exception 'buyer and seller must differ';
  end if;

  if new.trade_status in ('documentation','compliance_review','approved','in_transit','delivered','reconciled') then
    if new.buyer_organization_id is null or new.seller_organization_id is null then
      raise exception 'active trade requires buyer and seller';
    end if;
    if new.trade_corridor_id is null then
      raise exception 'active trade requires trade corridor';
    end if;
    select status into corridor_status from wim.trade_corridors where id = new.trade_corridor_id;
    if corridor_status <> 'active' then
      raise exception 'trade corridor must be active';
    end if;
  end if;

  if new.trade_status in ('approved','in_transit','delivered','reconciled') then
    select count(*) into failed_checks
    from wim.trade_compliance_checkpoints
    where transaction_id = new.id and status in ('pending','failed','restricted');
    if failed_checks > 0 then
      raise exception 'trade cannot progress with unresolved or failed compliance checkpoints';
    end if;
    if new.compliance_reference is null or btrim(new.compliance_reference) = '' then
      raise exception 'approved trade requires compliance reference';
    end if;
  end if;

  if new.trade_status = 'in_transit' and (new.logistics_reference is null or btrim(new.logistics_reference) = '') then
    raise exception 'in-transit trade requires logistics reference';
  end if;

  if new.trade_status = 'reconciled' then
    if new.settlement_status <> 'settled' then
      raise exception 'trade reconciliation requires authoritative settlement status';
    end if;
    if new.reconciled_at is null then new.reconciled_at := now(); end if;
  end if;

  if new.trade_status = 'exception' and (new.exception_reason is null or btrim(new.exception_reason)='') then
    raise exception 'exception trade state requires reason';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_wim_trade_progression on wim.transactions;
create trigger trg_wim_trade_progression
before insert or update on wim.transactions
for each row execute function wim.enforce_trade_progression();

create or replace function wim.audit_trade_state_change()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    insert into wim.trade_audit_events(transaction_id,event_type,event_payload)
    values(new.id,'trade.created',jsonb_build_object('trade_status',new.trade_status,'settlement_status',new.settlement_status));
  elsif old.trade_status is distinct from new.trade_status or old.settlement_status is distinct from new.settlement_status then
    insert into wim.trade_audit_events(transaction_id,event_type,event_payload)
    values(new.id,'trade.state_changed',jsonb_build_object('from_trade_status',old.trade_status,'to_trade_status',new.trade_status,'from_settlement_status',old.settlement_status,'to_settlement_status',new.settlement_status));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_wim_trade_audit on wim.transactions;
create trigger trg_wim_trade_audit
after insert or update on wim.transactions
for each row execute function wim.audit_trade_state_change();

comment on column wim.transactions.trade_status is 'Commercial trade workflow state, distinct from settlement_status and not proof of financial finality.';
comment on table wim.trade_logistics_references is 'External logistics/cash-logistics references only; records do not confer banking, custody, money-transmission, or insurance authority.';
comment on table wim.trade_corrections is 'Append-only correction evidence for trade workflow state; destructive history mutation is not the correction model.';
