create table if not exists sourcecubes.setc_patent_landscape_evidence (
  setc_id text primary key,
  source_specification text not null,
  source_url text,
  preliminary_ip_treatment text,
  filing_priority text,
  filing_status text,
  legacy_49_eligibility text not null default 'REQUIRES_DEDUPLICATION_AND_COUNSEL_REVIEW',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into sourcecubes.portfolio_evidence_registry(evidence_id,portfolio_class,asset_or_family,source_system,source_reference,evidence_status,ownership_status,filing_or_rights_status,counts_toward_legacy_49,notes)
values ('IP-EV-006','SETC_PATENT_LANDSCAPE','SETC Master Patent Landscape & Invention Capture Register — Version 1.0','Google Drive','1unKxBaCzRQ6Jg0RWhguUSyClmHjv2m1s','DOCUMENTED','OWNERSHIP_AND_INVENTORSHIP_REVIEW_REQUIRED','UNFILED',false,'SETC landscape is a preliminary invention-capture lane. It contains patent candidates, continuation/combination candidates, and trade-secret/copyright review items. Do not consume legacy 49 slots without deduplication against canonical IP families and counsel review.')
on conflict (evidence_id) do update set notes=excluded.notes, updated_at=now();

insert into sourcecubes.setc_patent_landscape_evidence(setc_id,source_specification,source_url,preliminary_ip_treatment,filing_priority,filing_status,notes) values
('SETC-001','SourceEnergy Trust Chain Blockchain System Architecture','https://docs.google.com/document/d/1yI3dsvDxxL1vztVpEeacgO7ebYfns5QJ9l-E8KWUjZs/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potentially within SETC-IP-001/SIOS-IP-001.'),
('SETC-002','SourceEnergy Trust Chain Canonical On-Chain Object Model','https://docs.google.com/document/d/1k0KMM78miZ1n_FWdOpCRcevdQfghiIof3xMruV540p4/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Deduplication required.'),
('SETC-003','SourceEnergy Trust Chain Identity & Authority Registry','https://docs.google.com/document/d/18MZDCVU_h8ifbyXLmjRXtxdIP49Jwsh7hVQ9NpaKHpQ/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential overlap with SETC-IP-001.'),
('SETC-004','SourceEnergy Trust Chain Dominion Grid & Geospatial Registry','https://docs.google.com/document/d/12vO0nQgay4_STK1M4c5pt_A37Ubm--EXkQe3jLr1CVU/edit','Trade Secret / Copyright Review','P3 — Capture & Preserve','UNFILED','Relevant to SSR/SourceCubes but not a current standalone patent candidate.'),
('SETC-005','SourceEnergy Trust Chain IP & Document Provenance Registry','https://docs.google.com/document/d/1iyJqw4_RqmUcCsCzn0HRSW2nzATbFaAH3bjjcbKmWDU/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential overlap with QIP/IP Blockchain provenance.'),
('SETC-006','SourceEnergy Trust Chain Smart Contract Governance Framework','https://docs.google.com/document/d/1OIFdCJDv-V1OVmPsYJEFRTLatVTwiQ14_a8IRh_S7dQ/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Separate generic smart-contract concepts from SourceEnergy-specific controls.'),
('SETC-007','SourceEnergy Trust Chain Tokenization & Digital Asset Governance Framework','https://docs.google.com/document/d/19g9x3HPEfN3RfRQdPHL7W7bGpBHezWUXxlK0AMpqku4/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential overlap with Source Coin/QIP/Capitalization.'),
('SETC-008','SourceEnergy Trust Chain Validator Network & Consensus Governance','https://docs.google.com/document/d/1yOBWx-6vo6DD-AwJEyBdPR6BkGCul5CFcgK87y0hs7E/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential overlap with IP Blockchain PF-11.'),
('SETC-009','SourceEnergy Trust Chain Cryptographic Key Management & Digital Signature Governance','https://docs.google.com/document/d/17GCbmYwL2wmrPkC10QUKDxfrghpPCxiWpfxmu5rUA5U/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Public cryptographic primitives must be separated from SourceEnergy orchestration.'),
('SETC-010','SourceEnergy Trust Chain Genesis Deployment & Production Readiness Protocol','https://docs.google.com/document/d/1eDtQwD0xf8g9QSqJNfyzt-mZy2BVWfTq8gAfc_pIkSs/edit','Continuation / Combination Candidate','P2 — Portfolio Review','UNFILED','No standalone family promotion absent distinct mechanism.'),
('SETC-011','SourceEnergy Trust Chain Blockchain Technical Implementation Blueprint','https://docs.google.com/document/d/1mxM0CEiflTs_X4r0RlUFqMes1cW48s63K3q7vIIdHrY/edit','Trade Secret / Copyright Review','P3 — Capture & Preserve','UNFILED','Implementation evidence unless counsel identifies patentable mechanism.'),
('SETC-012','SourceEnergy Trust Chain Canonical Data Schemas & Blockchain Object Model','https://docs.google.com/document/d/1CyAqAPkN_tvsaGjKqwva3pmrWG82RvlIYOTv4LKD6KQ/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential overlap with SETC-002/SETC-IP-001.'),
('SETC-013','SourceEnergy Trust Chain Identity, Authority & Access-Control Technical Specification','https://docs.google.com/document/d/1LdKLLd8YUt0liUG9q3lBl5RsH9S2EGQzXUBpj4qV-Lw/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential overlap with SETC-003/SETC-IP-001.'),
('SETC-014','SourceEnergy Trust Chain Smart Contract & Chaincode Implementation Specification','https://docs.google.com/document/d/1Q7F3y7AdyYUYWfyfD1I__HKmXzusYT1dlv3o5u3IjsE/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential overlap with SETC-006.'),
('SETC-015','SourceEnergy Trust Chain API Gateway, Integration & Event Architecture Specification','https://docs.google.com/document/d/1oNJN6Z7l-8pT-vxEuvev1ulhoKN0uYnipe_NvBTNCOk/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential SIOS implementation/subfamily evidence.'),
('SETC-016','SourceEnergy Trust Chain DevSecOps, CI/CD, Infrastructure-as-Code & Environment Deployment Specification','https://docs.google.com/document/d/1xm21I5vb5pFNKBEFk6SUljKUTDbT0lRTGSOUN4DPpt0/edit','Continuation / Combination Candidate','P2 — Portfolio Review','UNFILED','Likely SIOS implementation evidence.'),
('SETC-017','SourceEnergy Trust Chain Observability, Security Operations, Incident Response & Blockchain Network Operations Specification','https://docs.google.com/document/d/123afANaB-YPKyRRNdy1mXNjKLY_1E7Lr4xJsP_1G8SA/edit','Continuation / Combination Candidate','P2 — Portfolio Review','UNFILED','Likely continuation/combination evidence.'),
('SETC-018','SourceEnergy Trust Chain Testing, Verification, Validation & Production Certification Specification','https://docs.google.com/document/d/1OlfoKHJ3w9YBigUwBtZfp-ZcVv7Z2ty8K4BjT4YBlD8/edit','Trade Secret / Copyright Review','P3 — Capture & Preserve','UNFILED','Preserve; not standalone candidate.'),
('SETC-019','SourceEnergy Trust Chain Production Launch, Genesis Activation & Network Commissioning Specification','https://docs.google.com/document/d/14uQjfeegizJUApLZO3DSRLYOy1d8XdOvtE7tlpgoYP4/edit','Trade Secret / Copyright Review','P3 — Capture & Preserve','UNFILED','Preserve; not standalone candidate.'),
('SETC-020','SourceEnergy Trust Chain Production Governance, Network Expansion, Upgrade & Lifecycle Management Specification','https://docs.google.com/document/d/1egz4k7UUsmtrBoO_kRsI5Jry6x0CiMuQ6ydgkH02jgQ/edit','Continuation / Combination Candidate','P2 — Portfolio Review','UNFILED','Portfolio review required.'),
('SETC-021','SourceEnergy Trust Chain Enterprise Integration, Treasury, Settlement & Economic Network Specification','https://docs.google.com/document/d/1E3R3gnaasppRpqv0aqWw5hRei31xdPDJFii6VcaEkXQ/edit','Continuation / Combination Candidate','P2 — Portfolio Review','UNFILED','Potential overlap with SETC-IP-CAP-001/WIM/Source Coin/IOTF.'),
('SETC-022','SourceEnergy Trust Chain Digital Asset, Tokenization, Reserve Attestation & Programmable Economic Instrument Specification','https://docs.google.com/document/d/1h81CmlKV2BU5BQmjftRVXVt8MS48bssljSOZPiEqlI0/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential overlap with Source Coin/QIP/IOTF.'),
('SETC-023','SourceEnergy Trust Chain Wallet, Digital Custody, Holder Account & Transaction Authorization Specification','https://docs.google.com/document/d/1lsrPzQDt_VsZVGnge-BRXlDBlMvacbsrmx5MpExtvag/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential Source Coin/capital-control subfamily.'),
('SETC-024','SourceEnergy Trust Chain Blockchain Explorer, Audit Console, Transparency Portal & Evidence Verification Specification','https://docs.google.com/document/d/1hNXn1GPy8hvITwZcMcYDsh8yBt9lD5mUkQsIKhBRYVk/edit','Continuation / Combination Candidate','P2 — Portfolio Review','UNFILED','Potential provenance/assurance continuation.'),
('SETC-025','SourceEnergy Trust Chain Network Operations Center, Validator Command, Monitoring, Incident Response & Resilience Specification','https://docs.google.com/document/d/1JQIP1eOmckfx6srYIzMEnCt4izzSjhc3aFvv43nQ9cg/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential overlap with SETC-008/PF-11.'),
('SETC-026','SourceEnergy Trust Chain Developer Platform, SDK, Smart Contract Toolchain, Sandbox & Partner Integration Specification','https://docs.google.com/document/d/1McjclrzDPunpgxO-tXj9C9rsK_Mk2luKapJ3JaTH12k/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential SIOS/SETC developer-platform subfamily.'),
('SETC-027','SourceEnergy Trust Chain Blockchain Data Intelligence, Analytics, AI/ML, Risk Scoring & Decision-Support Specification','https://docs.google.com/document/d/1ha2IpWHTfCQRFoq2Y8vYkY9Uj0iwsEl8mTaeymsri2I/edit','Patent Candidate','P1 — Immediate Review','UNFILED','Potential SIOS intelligence subfamily.')
on conflict (setc_id) do update set source_specification=excluded.source_specification, source_url=excluded.source_url, preliminary_ip_treatment=excluded.preliminary_ip_treatment, filing_priority=excluded.filing_priority, filing_status=excluded.filing_status, notes=excluded.notes, updated_at=now();
